/// <reference types="react" />
import * as React from 'react';
import './GridControl.css';
export interface IGridControlViewOption {
    key: string;
    text: string;
    isDefault?: boolean;
}
export interface IGridControlColumnConfiguration {
    fieldName: string;
    displayName: string;
    width?: string;
}
export interface IGridControlProps {
    context: any;
    listName: string;
    defaultViewId: string;
    views: IGridControlViewOption[];
    viewColumns: IGridControlColumnConfiguration[];
    gridSchemaJson: string;
    pageSize: number;
    fetchBatchSize: number;
    isEditMode: boolean;
    showViewSelector: boolean;
    showViewAsDropdown: boolean;
    showRefresh: boolean;
    showAdd: boolean;
    showDelete: boolean;
    showHistory: boolean;
    historyAvailable: boolean;
    actionButtonsPosition: string;
    buttonDisplayMode: string;
    readSecurityGroupId: string;
    editSecurityGroupId: string;
    readAccessDeniedMessage: string;
    editAccessDeniedMessage: string;
    showLinkToItem: boolean;
    linkTargetPageUrl: string;
    linkTargetIdParam: string;
    includeReturnUrlParam: boolean;
    enableDiagnostics: boolean;
    bodyTextColor: string;
    bodyFontFamily: string;
    bodyFontSize: string;
    bodyFontStyle: string;
    bodyFontBold: boolean;
    bodyTextAlign: string;
    dateDisplayFormat: string;
    dateCustomFormat?: string;
    dateCustomFormatCase?: string;
    timeDisplayFormat: string;
    timeCustomFormat?: string;
    timeCustomFormatCase?: string;
    selectedTextColor: string;
    selectedBackgroundColor: string;
    selectedFontStyle: string;
    selectedFontBold: boolean;
    headerTextColor: string;
    headerBackgroundColor: string;
    headerFontFamily: string;
    headerFontSize: string;
    headerFontStyle: string;
    headerFontBold: boolean;
    headerTextAlign: string;
    tableBackgroundColor: string;
    tableBorderColor: string;
    tableBorderWidth: string;
    tableCornerStyle: string;
    tableCornerRadius: number;
    tableRowLineWidth: number;
    cornerStyle: string;
    cornerRadius: number;
    alternateRowShading: boolean;
    alternateRowShadingColor: string;
    buttonTextColor: string;
    buttonBackgroundColor: string;
    buttonFontFamily: string;
    buttonFontSize: string;
    buttonFontStyle: string;
    buttonFontBold: boolean;
    buttonCornerStyle: string;
    buttonCornerRadius: number;
    webpartBackgroundColor: string;
    webpartBorderColor: string;
    webpartBorderWidth: number;
    filterJson?: string;
    conditionalStyleJson?: string;
    onSelectionChange: (itemId: number, mode: string) => void;
}
export interface IListFieldDefinition {
    Name: string;
    RealFieldName?: string;
    DisplayName?: string;
    TypeAsString?: string;
    DisplayFormat?: number;
    Hidden?: string | boolean;
    ConfiguredWidth?: string;
}
export interface IGridFieldMetadata {
    internalName: string;
    title: string;
    typeAsString: string;
    required: boolean;
    readOnly: boolean;
    hidden: boolean;
    description: string;
    choices: string[];
    displayFormat: number;
    lookupList: string;
    lookupField: string;
    allowMultiple: boolean;
    richText: boolean;
}
export interface IGridLookupOption {
    id: number;
    text: string;
}
export interface IGridControlState {
    selectedViewId: string;
    fields: IListFieldDefinition[];
    fieldMetadataByName: {
        [fieldName: string]: IGridFieldMetadata;
    };
    lookupOptionsByField: {
        [fieldName: string]: IGridLookupOption[];
    };
    rows: any[];
    loading: boolean;
    loadingMore: boolean;
    nextPageHref: string;
    error: string | null;
    selectedItemId: number;
    selectedItemIds: number[];
    selectedMode: string;
    deleting: boolean;
    deleteMessage: string;
    sortFieldName: string;
    sortDirection: 'asc' | 'desc' | '';
    activeFilterFieldName: string;
    filterPopoverStyle: any;
    activeFilterIsDate: boolean;
    draftFilterOperator: FilterOperator;
    draftFilterValue: string;
    draftFilterEndValue: string;
    datePickerTarget: 'start' | 'end' | '';
    datePickerMonth: string;
    columnFilters: {
        [fieldName: string]: IColumnFilter;
    };
    currentPage: number;
    collapsedGroupKeys: {
        [groupKey: string]: boolean;
    };
    editingItemId: number;
    editingValues: {
        [fieldName: string]: any;
    };
    editingErrors: {
        [fieldName: string]: string;
    };
    saving: boolean;
    embeddedByDynamicForms: boolean;
    runtimeFilterJson: string;
    runtimeDefaultField: string;
    runtimeDefaultValue: any;
    runtimeReadOnly: boolean;
    runtimeConfigOwner: string;
    accessLoading: boolean;
    hasReadAccess: boolean;
    hasEditAccess: boolean;
    attachmentCountsByItemId: {
        [itemId: number]: number;
    };
    showScrollArrows: boolean;
    scrollArrowTop: number;
    scrollArrowLeft: number;
    scrollArrowRight: number;
    historyDialogOpen: boolean;
    historyDialogUrl: string;
    historyDialogLoading: boolean;
    historyDialogError: string;
}
export declare type FilterOperator = 'eq' | 'ne' | 'contains' | 'notcontains' | 'startswith' | 'endswith' | 'gt' | 'ge' | 'lt' | 'le';
export interface IColumnFilter {
    operator: FilterOperator;
    value: any;
    endValue?: string;
    compareDateOnly?: boolean;
}
export declare class GridControl extends React.Component<IGridControlProps, IGridControlState> {
    private _refreshEventHandler;
    private _runtimeConfigEventHandler;
    private _loadRowsRequestId;
    private _listItemEntityTypeName;
    private _listItemEntityTypeListName;
    private _listId;
    private _listIdListName;
    private _tableWrapEl;
    private _tableHeadEl;
    private _stickyHeaderViewportEl;
    private _stickyHeaderSourceHtml;
    private _stickyHeaderVisible;
    private _filterAnchorEl;
    private _pagingEndpoint;
    private _pagingRequestBody;
    private _pagingSchemaFieldNames;
    private _scrollArrowResizeHandler;
    private _scrollArrowScrollHandler;
    constructor(props: IGridControlProps);
    componentDidMount(): void;
    componentWillUnmount(): void;
    componentDidUpdate(prevProps: IGridControlProps, prevState: IGridControlState): void;
    private _setTableWrapRef;
    private _setTableHeadRef;
    private _setStickyHeaderViewportRef;
    private handleStickyHeaderClick;
    private getStickyHeaderControls(root);
    private refreshTableViewport();
    private refreshScrollArrows();
    private updateScrollArrowVisibility();
    private updateScrollArrowPosition();
    private updateStickyHeaderPosition();
    private getStickyViewportTop(wrapRect);
    private getScrollViewportTop(viewportHeight);
    private scrollTableHorizontally(direction);
    private getInitialViewId(views);
    private getSelectedViewLabel();
    private handleExternalRefresh(event);
    private handleRuntimeConfig(event);
    private cancelRuntimeEdit();
    private getWebUrl();
    private loadAccessAndRows();
    private isReadOnly();
    private getCommandButtonClass(className?);
    private renderCommandContent(iconName, label);
    private getJsonWithFallback(url);
    private logPostAttempt(label, url, response, payload);
    private postJsonWithFallback(url, body, baseHeaders?, verboseBody?, allowFallback?);
    private buildViewIdCandidates(selectedViewId);
    private buildMinimalViewXml(viewQuery, viewFieldNames, rowLimit, scope);
    private loadSelectedViewXml(selectedViewId, viewFieldNames);
    private addFieldsToViewXml(viewXml, fieldNames);
    private loadSelectedViewFieldNames(selectedViewId);
    private getDisplayFields();
    private getGridSchemaFields();
    private getGridSchema();
    private getAdvancedValidationRules();
    private getGridGroupingConfig();
    private getGridSchemaField(fieldName);
    private getConfiguredColumnStyle(field);
    private getFieldsForConsumption(rawFields, viewFieldNames);
    private loadListFieldTypeMap(viewFieldNames);
    private loadListFieldTitleMap();
    private loadGridFieldMetadata();
    private loadListItemEntityTypeName();
    private loadLookupOptions(metadata);
    private loadLookupOptionsByField(metadataByName, visibleFields);
    private applyFieldDisplayNames(fields, titleMap);
    private applyFieldTypes(fields, metadataByName);
    private getRowFieldValue(row, field);
    private getUrlCellValue(row, field);
    private stringifyCellValue(value);
    private formatDateCellValue(value, field, row?);
    private isMeaningfulCellValue(value);
    private filterRenderableRows(rows, visibleFields);
    private loadRowsFromItemsEndpoint(viewFieldNames, itemIds?);
    private loadAttachmentCounts(itemIds);
    private loadRows();
    private applyFetchBatchSize(viewXml);
    private loadNextBatch();
    private loadAllRemainingRows();
    private goToNextPage(currentPage, pageCount);
    private getRowItemId(row);
    private selectRow(row);
    private isItemChecked(itemId);
    private toggleItemChecked(itemId);
    private toggleVisibleItemsChecked(rows);
    private getGridFieldMetadata(field);
    private isEditableGridField(field);
    private getLookupIds(value);
    private normalizeEditingValue(value, metadata);
    private beginRowEdit(row);
    private beginNewRow();
    private cancelRowEdit();
    private updateEditingValue(fieldName, value);
    private validateEditingValues();
    private buildEditingPayload();
    private buildVerboseEditingPayload(payload, entityTypeName);
    private saveEditingRow();
    private renderEditingControl(field);
    private renderEditingRow(displayFields, sourceRow, fieldsByKey, conditionalRules);
    private openVersionHistory(row);
    private closeVersionHistory();
    private renderRowActionCell(row, isEditingRow, isReadOnly);
    private deleteSelected();
    private logDiagnostic(message);
    private getCellMarkup(row, field);
    private isTitleField(field);
    private getCellPlainText(row, field);
    private getAttachmentCountForRow(row, rawAttachmentsValue);
    private getItemLinkUrl(row);
    private getFieldKey(field);
    private getFilterOperatorOptions();
    private toggleSort(field);
    private openFilter(field, anchorElement);
    private getFilterPopoverStyle(anchorElement);
    private updateActiveFilterPosition();
    private closeFilter();
    private getIsoDate(date);
    private toggleDatePicker(target);
    private changeDatePickerMonth(offset);
    private selectFilterDate(value);
    private renderDatePicker();
    private applyActiveFilter();
    private clearActiveFilter();
    private compareComparableValues(leftValue, rightValue);
    private rowMatchesFilter(row, field, filter);
    private getFilterCellText(row, field);
    private parsePresetFilterConditions();
    private resolveFieldByReference(fieldsByKey, fieldRef);
    private rowMatchesPresetConditions(row, fieldsByKey, conditions);
    private resolvePresetFilterValue(condition);
    private getProcessedRows();
    private resolveFieldDefinitionByName(fieldName);
    private getGroupValueText(row, fieldName);
    private buildRowGroups(rows, grouping);
    private countGroupRows(group);
    private isGroupCollapsed(groupKey, collapsedByDefault);
    private toggleGroupCollapsed(groupKey, collapsedByDefault);
    private parseConditionalStyleRules();
    private toReactCssStyle(styleDefinition);
    private evaluateConditionalStyleRule(row, rule, fieldsByKey);
    private getConditionalStyleForRow(row, fieldsByKey, rules);
    private getMatchedConditionalRuleNames(row, fieldsByKey, rules);
    private renderDataRow(row, keySuffix, isEditingRow, isReadOnly, displayFields, fieldsByKey, conditionalRules);
    private renderGroupHeaderRow(group, keyPath, level, totalColumnCount, groupingConfig);
    private renderRowGroupRows(group, keyPath, level, groupingConfig, totalColumnCount, isEditingRow, isReadOnly, displayFields, fieldsByKey, conditionalRules);
    render(): JSX.Element;
}
