define([], function() {
  return {
    "PropertyPaneDescription": "Configure grouped navigation for Dynamic Forms and Report Forms on this page.",
    "VersionGroup": "Version",
    "DataGroup": "Categories and forms",
    "BehaviorGroup": "Navigation behavior",
    "AppearanceGroup": "Navigation appearance",
    "StateAppearanceGroup": "State colors",
    "SpacingGroup": "Spacing and borders",
    "TitleLabel": "Navigation title",
    "CategoriesLabel": "Form categories",
    "CategoriesHeader": "Manage form categories",
    "CategoriesDescription": "Add categories and drag rows to set their display order.",
    "ManageCategoriesLabel": "Manage categories",
    "CategoryNameLabel": "Category name",
    "CategoryCollapsedLabel": "Initially collapsed",
    "FormsLabel": "Navigation forms",
    "FormsHeader": "Manage navigation forms",
    "FormsDescription": "Select a form or report and category, then drag rows to set the navigation order.",
    "ManageFormsLabel": "Manage forms",
    "FormSelectionLabel": "Dynamic Form or Report Form",
    "FormCategoryLabel": "Category",
    "FormLabelLabel": "Navigation label",
    "FormRequiredLabel": "Required",
    "FormPolicyLabel": "Navigation policy",
    "PolicyDefault": "Use navigator default",
    "NavigationPolicyLabel": "Default navigation policy",
    "PolicyFree": "Free navigation",
    "PolicyCompleted": "Completed forms only",
    "PolicySequential": "Sequential unlock",
    "PolicyPreview": "Locked forms open read-only",
    "LayoutLabel": "Layout",
    "LayoutVertical": "Vertical groups",
    "LayoutHorizontal": "Horizontal categories",
    "LayoutTree": "Tree",
    "ShowStatusLabel": "Show status icons",
    "ShowCategoryCountsLabel": "Show category completion counts",
    "ConfirmDirtyLabel": "Confirm before leaving unsaved changes",
    "SurfaceBackgroundLabel": "Surface background",
    "SurfaceTextLabel": "Surface text",
    "CategoryBackgroundLabel": "Category background",
    "CategoryTextLabel": "Category text",
    "NodeBackgroundLabel": "Form background",
    "NodeTextLabel": "Form text",
    "ActiveBackgroundLabel": "Active background",
    "ActiveTextLabel": "Active text",
    "CompleteColorLabel": "Complete status",
    "LockedColorLabel": "Locked status",
    "ErrorColorLabel": "Error status",
    "BorderColorLabel": "Border color",
    "BorderWidthLabel": "Border width",
    "CornerRadiusLabel": "Corner radius",
    "FontFamilyLabel": "Font family",
    "FontSizeLabel": "Form font size",
    "CategoryFontSizeLabel": "Category font size",
    "FontBoldLabel": "Bold form labels",
    "CategoryFontBoldLabel": "Bold category labels",
    "NodePaddingLabel": "Form padding",
    "NodeGapLabel": "Space between forms",
    "CategoryGapLabel": "Space between categories",
    "IndentSizeLabel": "Tree indent",
    "DiagnosticsGroup": "Diagnostics",
    "DiagnosticsLabel": "Enable diagnostic logging",
    "NoConfiguration": "Add categories and forms in the property pane.",
    "NoFormsInCategory": "No forms configured in this category.",
    "UnsavedConfirm": "This form has unsaved changes. Leave it and discard those changes?",
    "TargetNotFound": "The selected form or report is not available on this page.",
    "InvalidCategories": "Every category must have a unique name.",
    "InvalidForms": "Every row must select a unique form or report, a category, and a navigation label.",
    "StatusComplete": "Complete",
    "StatusActive": "Current",
    "StatusError": "Needs attention",
    "StatusLocked": "Locked",
    "StatusAvailable": "Available",
    "CollapseCategory": "Collapse category",
    "ExpandCategory": "Expand category"
  };
});
