import SlideItemModel from './SlideItem';
import RecordSvc from '../../../services/RecordService';
import { WebPartContext } from "@microsoft/sp-webpart-base";

export interface ICarouselProps {
  carouselWidth: number;
  carouselHeight:number;
  carouselSlideInterval: string;
  carouselSlideItems: Array<SlideItemModel>;
  carouselTransitionInterval: string;
  carouselSlideLibrary: string;
  slideTitleField: string;
  slideDescriptionField: string;
  slideLinkField: string;
  imageIsCircle: boolean;
  webPartBackgroundColor: string;
  webPartBorderColor: string;
  webPartBorderWidth: number;
  webPartBorderStyle: string;
  webPartCornerRadius: number;
  webPartPadding: number;
  showTitle: boolean;
  title: string;
  titleTextColor: string;
  titleFontFamily: string;
  titleFontSize: number;
  titleFontStyle: string;
  titleFontBold: boolean;
  titleAlignment: string;
  titleBottomSpacing: number;
  showSlideTitle: boolean;
  slideTitleColor: string;
  slideTitleFontFamily: string;
  slideTitleFontSize: number;
  slideTitleFontStyle: string;
  slideTitleFontBold: boolean;
  slideTitleAlignment: string;
  showSlideDescription: boolean;
  slideDescriptionColor: string;
  slideDescriptionFontFamily: string;
  slideDescriptionFontSize: number;
  slideDescriptionFontStyle: string;
  slideDescriptionFontBold: boolean;
  slideDescriptionAlignment: string;
  showSlideLink: boolean;
  slideLinkColor: string;
  slideLinkFontFamily: string;
  slideLinkFontSize: number;
  slideLinkFontStyle: string;
  slideLinkFontBold: boolean;
  slideLinkAlignment: string;
  slideCaptionBackgroundColor: string;
  slideCaptionPadding: number;
  enableDiagnostics: boolean;
  spfxContext: WebPartContext;
  recSvc: RecordSvc;
}
