define([], function() {
  return {
    "PropertyPaneDescription": "Dynamic form settings",
    "BasicGroupName": "Basic",
    "DescriptionFieldLabel": "Description",
    "PropertyGroupBasic": "Basic settings",
    "PropertyGroupDefaults": "Default values",
    "PropertyGroupButtons": "Button settings",
    "PropertyGroupConfigIO": "Config import/export",
    "PropListLabel": "SharePoint list",
    "PropModeLabel": "Form mode",
    "PropModeNew": "New",
    "PropModeEdit": "Edit",
    "PropModeView": "View",
    "PropItemIdQueryParamLabel": "Item ID query parameter",
    "PropDynamicItemIdLabel": "Dynamic Item ID (from another web part)",
    "PropDynamicSourceNone": "No ListControl, GridControl, or Calendar source available",
    "PropUseDynamicItemAsItemIdLabel": "Use dynamic ID as form item ID",
    "PropUseDynamicItemAsItemIdHelp": "When ON: The dynamic value (e.g., ID=1 from ListControl, GridControl, or Calendar) is used directly as the record ID to load/edit in this form's list. When OFF: The dynamic value is used only as a field value or filter condition.",
    "PropDynamicItemTargetFieldLabel": "Target column",
    "PropDynamicItemTargetFieldPlaceholder": "Select a column",
    "PropDynamicItemTargetFieldHelp": "Select the column in the current form list that should receive or match the value from ListControl, GridControl, or Calendar.",
    "PropDynamicTargetFieldNone": "No columns available for the selected list",
    "PropertyPanelChoiceDisplay": "Choice display",
    "PropertyPanelChoiceDisplayDropdown": "Dropdown",
    "PropertyPanelChoiceDisplayRadio": "Radio buttons",
    "PropertyPanelChoiceDisplayMultiHint": "Multi-choice fields are shown as checkboxes. Select one value below to make it exclusive and clear all other selections.",
    "PropertyPanelExclusiveChoiceValue": "Exclusive choice value",
    "PropertyPanelExclusiveChoiceValuePlaceholder": "Example: None",
    "PropertyPanelExclusiveChoiceValueHint": "When this value is selected, all other options are cleared and disabled.",
    "PropPermissionBaseLookupFieldLabel": "Base permission on",
    "PropPermissionBaseLookupFieldClear": "None (use the form list permissions)",
    "PropPermissionBaseLookupFieldNone": "No lookup columns available for the selected list",
    "PropPermissionScopeLabel": "Permission scope",
    "PropPermissionScopeList": "List",
    "PropPermissionScopeItem": "Item",
    "PropUseDynamicValueAsFilterLabel": "Use dynamic value to find record (filter mode)",
    "PropUseDynamicValueAsFilterHelp": "When ON: The dynamic value is used to SEARCH for a matching record by looking for records where a specific column equals the dynamic value. The target column is either set by 'Dynamic ID target field' or defined in the 'Record filter JSON'. When OFF: Dynamic value is only used as a field value (no filtering).",
    "PropFilterJsonLabel": "Record filter JSON",
    "PropFilterJsonPlaceholder": "[{\"field\":\"Main\",\"type\":\"lookup\",\"value\":\"dynamic\"}]",
    "PropFilterJsonHelp": "JSON array of filter conditions to find the record to edit/view. Use \"dynamic\" as value to reference the dynamic data source value. Types: lookup, choice, text, number, boolean.",
    "PropFilterDesignerTitle": "Filter JSON designer",
    "PropFilterDesignerFieldLabel": "Filter field",
    "PropFilterDesignerTypeLabel": "Field type",
    "PropFilterDesignerValueSourceLabel": "Value source",
    "PropFilterDesignerValueSourceDynamic": "Dynamic value",
    "PropFilterDesignerValueSourceStatic": "Static value",
    "PropExpressionValueType": "Expression",
    "PropExpressionLabel": "Expression",
    "PropExpressionPlaceholder": "Example: today, date(-3), or me.email",
    "PropExpressionHelp": "Supported expressions: today, now, date(n), me, me.email, me.login, and me.id. date(n) offsets today by n days, for example date(-3) or date(7).",
    "PropExpressionHelpShow": "Show supported expressions",
    "PropExpressionHelpHide": "Hide supported expressions",
    "PropExpressionInvalid": "Enter a supported expression: today, now, date(n), me, me.email, me.login, or me.id.",
    "PropFilterDesignerValueLabel": "Static value",
    "PropFilterDesignerAddButtonLabel": "Add condition to JSON",
    "PropFilterDesignerExistingLabel": "Existing conditions",
    "PropFilterDesignerExistingNone": "No conditions in JSON",
    "PropFilterDesignerLoadButtonLabel": "Load selected condition",
    "PropFilterDesignerUpdateButtonLabel": "Update selected condition",
    "PropFilterDesignerRemoveButtonLabel": "Remove selected condition",
    "PropFilterDesignerResetButtonLabel": "Clear filter JSON",
    "PropFilterDesignerStatusPlaceholder": "Filter designer result appears here.",
    "PropValidateFilterJsonButtonLabel": "Validate record filter JSON",
    "PropDynamicModeLabel": "Dynamic Mode (new/edit/view)",
    "PropItemIdLabel": "Item ID",
    "PropItemIdPlaceholder": "Optional: enter a fixed item ID (for edit/view)",
    "PropItemIdHelp": "Optional fixed record ID for direct open.",
    "PropLabelPositionLabel": "Label position",
    "PropLabelTop": "Top",
    "PropLabelLeft": "Left",
    "PropShowFieldDescriptionLabel": "Show field description",
    "PropEnableDynamicDiagnosticsLabel": "Enable dynamic diagnostics",
    "PropToggleOn": "On",
    "PropToggleOff": "Off",
    "PropAddSubmitButtonLabel": "Add button text",
    "PropAddSubmitButtonPlaceholder": "Add (default)",
    "PropEditSubmitButtonLabel": "Edit button text",
    "PropEditSubmitButtonPlaceholder": "Save (default)",
    "PropSubmitButtonLabel": "Submit button text",
    "PropSubmitButtonPlaceholder": "Submit (default)",
    "PropShowCancelButtonLabel": "Show cancel button",
    "PropCancelButtonLabel": "Cancel button text",
    "PropCancelButtonPlaceholder": "Cancel (default)",
    "PropCancelRedirectUrlLabel": "Redirect URL after cancel",
    "PropCancelRedirectUrlPlaceholder": "Leave empty to reset form",
    "PropSubmitRedirectUrlLabel": "Redirect URL after submit",
    "PropSubmitRedirectUrlPlaceholder": "Leave empty to show success message",
    "PropSubmitSuccessMessageLabel": "Submit success message",
    "PropSubmitSuccessMessagePlaceholder": "Form submitted successfully! (default)",
    "PropButtonTextColorLabel": "Button text color",
    "PropButtonBackgroundColorLabel": "Button background color",
    "PropButtonBorderColorLabel": "Button border color",
    "PropButtonBorderWidthLabel": "Button border width",
    "PropButtonFontFamilyLabel": "Button font family",
    "PropButtonFontSizeLabel": "Button font size",
    "PropButtonFontStyleLabel": "Button font style",
    "PropButtonFontBoldLabel": "Button font bold",
    "PropButtonCornerStyleLabel": "Button corner style",
    "PropButtonCornerRadiusLabel": "Button corner radius (px)",
    "PropCornerStyleSquare": "Square",
    "PropCornerStyleRounded": "Rounded",
    "PropFontStyleNormal": "Normal",
    "PropFontStyleItalic": "Italic",
    "PropDefaultValuesJsonLabel": "Default values JSON (Add mode)",
    "PropDefaultValuesJsonPlaceholder": "{\n  \"Category\": \"IT\",\n  \"RequestType\": \"New\",\n  \"DepartmentLookup\": 1,\n  \"IsActive\": true\n}",
    "PropDefaultValuesJsonHelp": "Set defaults by field internal name or field id. Applies when creating new records (including Edit/View with no resolved item ID).",
    "PropDefaultDesignerTitle": "Default values JSON designer",
    "PropDefaultDesignerFieldLabel": "Default field",
    "PropDefaultDesignerValueTypeLabel": "Default value type",
    "PropDefaultDesignerValueTypeString": "String",
    "PropDefaultDesignerValueTypeNumber": "Number",
    "PropDefaultDesignerValueTypeBoolean": "Boolean",
    "PropDefaultDesignerValueTypeJson": "JSON",
    "PropDefaultDesignerValueLabel": "Default value",
    "PropDefaultDesignerAddButtonLabel": "Add/update default in JSON",
    "PropDefaultDesignerExistingLabel": "Existing defaults",
    "PropDefaultDesignerExistingNone": "No defaults in JSON",
    "PropDefaultDesignerLoadButtonLabel": "Load selected default",
    "PropDefaultDesignerRemoveButtonLabel": "Remove selected default",
    "PropDefaultDesignerResetButtonLabel": "Clear defaults JSON",
    "PropDefaultDesignerStatusPlaceholder": "Defaults designer result appears here.",
    "PropValidateDefaultValuesJsonButtonLabel": "Validate default values JSON",
    "JsonValidationResultPlaceholder": "Validation result appears here.",
    "JsonValidationSuccess": "JSON is valid.",
    "JsonValidationEmpty": "Empty value is allowed.",
    "JsonValidationExpectedArray": "JSON must be an array.",
    "JsonValidationExpectedObject": "JSON must be an object.",
    "JsonValidationFailedPrefix": "JSON is invalid",
    "ConfigExportButton": "Export config",
    "ConfigImportButton": "Import config",
    "ConfigImportSuccess": "Configuration imported.",
    "ConfigImportInvalid": "Invalid configuration file.",
    "ConfigImportReadError": "Failed to read configuration file.",
    "ConfigImportWarningList": "List not found. Please reselect the list in settings.",
    "DesignerTitle": "Form Designer",
    "DesignerButton": "Design Form",
    "DesignerBackButton": "Back",
    "CommonSave": "Save",
    "CommonSaving": "Saving...",
    "CommonLoading": "Loading...",
    "CommonRetry": "Retry",
    "CommonContinueEditing": "Continue editing",
    "CommonReadOnly": "Read-only",
    "CommonCancel": "Cancel",
    "CommonSubmit": "Submit",
    "CommonSubmitting": "Submitting...",
    "CommonContinueCreate": "Continue creating",
    "CommonUnknownError": "Unknown error",
    "RuntimeNoSchemaWarning": "Please configure the form in web part properties",
    "LoadErrorNoItemIdFromUrl": "Item ID could not be resolved from URL, page context, or web part settings. Unable to load form data.",
    "LoadConfigFailed": "Failed to load form configuration",
    "SaveFailedDefault": "Save failed, please try again",
    "UploadAttachmentFailedTemplate": "Failed to upload attachment \"{0}\": {1}",
    "FormInvalidMessageDefault": "Invalid format",
    "FormStepValidationError": "Please complete all required fields before continuing",
    "FormSubmitFailedDefault": "Submit failed, please try again",
    "FormRedirectFailed": "Redirect failed: the target URL is not allowed.",
    "FormSubmitLabelEdit": "Save",
    "FormSubmitLabelAdd": "Add",
    "FormSwitchToEditLabel": "Edit",
    "FormSubmitSuccessEdit": "Updated successfully!",
    "FormSubmitSuccessNew": "Submitted successfully!",
    "FormStepHiddenTitle": "Current container is hidden",
    "FormStepHiddenDescription": "Please adjust field conditions to make this container visible.",
    "FormUploadingAttachments": "Uploading attachments",
    "FormErrorSummaryTitle": "There are {0} errors in this form:",
    "DialogCancelTitle": "Confirm cancel",
    "DialogCancelSubText": "You have unsaved changes. Discard them?",
    "DialogDiscardChanges": "Discard changes",
    "StepPrev": "Previous",
    "StepNext": "Next",
    "StepEmptyNoVisibleFields": "No visible fields in this container",
    "FieldPlaceholderSelect": "Please select",
    "FieldUrlDescriptionLabel": "Description (optional)",
    "FieldUrlDescriptionPlaceholder": "Display text for the link",
    "FieldUrlInvalidFormat": "URL must start with http:// or https://",
    "FieldErrorBoundaryMessage": "Failed to render \"{0}\" field. Please check the field configuration.",
    "FieldRichTextEmpty": "No content",
    "FieldImageReadFileFailed": "Failed to read file content",
    "FieldImageUploadFailed": "Failed to upload image",
    "FieldImageInvalidFileType": "Invalid file type. Only JPG, PNG, GIF, BMP, and WebP images are allowed.",
    "FieldImageNoImage": "No image",
    "FieldImageRuntimeOnly": "Image picker is available in runtime mode",
    "FieldPersonMissingContext": "Missing SharePoint context",
    "FieldPersonPlaceholder": "Type name or email to search (at least 3 chars)...",
    "FieldAttachmentMissingContext": "Missing SharePoint context",
    "FieldAttachmentNeedListName": "Please configure list name in form settings",
    "FieldAttachmentLoadListFailed": "Unable to load list ID for \"{0}\"",
    "FieldAttachmentLoadingList": "Loading list information...",
    "FieldAttachmentNeedListInfo": "Please configure list name or list ID (GUID) to enable attachments.",
    "FieldAttachmentUploadOnSubmit": "Attachments will be uploaded on submit.",
    "FieldAttachmentAddButton": "Add attachment",
    "FieldAttachmentClear": "Clear",
    "FieldAttachmentDelete": "Delete",
    "FieldAttachmentUndoDelete": "Undo",
    "FieldAttachmentWillDelete": "Will be deleted on submit",
    "FieldAttachmentRemoveAria": "Remove attachment",
    "FieldAttachmentEmpty": "No attachments selected",
    "FieldTaxonomyMissingContext": "Missing SharePoint context",
    "FieldTaxonomyMissingTermSetId": "Missing Term Set ID (TermSetId)",
    "FieldTaxonomyWorkbenchTitle": "Workbench limitation",
    "FieldTaxonomyWorkbenchDesc": "Taxonomy field is not available in local workbench. Deploy to SharePoint to test.",
    "FieldTaxonomyDeployLink": "Deploy to SharePoint",
    "FieldTaxonomyWorkbenchPlaceholder": "(Available only in real SharePoint environment)",
    "FieldTaxonomyWorkbenchDescription": "This is a placeholder. Deploy to SharePoint for full functionality.",
    "FieldTaxonomyInvalidTermSetId": "Invalid Term Set ID format: {0}",
    "FieldTaxonomyPanelTitle": "Select {0}",
    "FieldTaxonomyPlaceholder": "Select terms...",
    "FieldBooleanYes": "Yes",
    "FieldBooleanNo": "No",
    "PermissionDeniedDefault": "You do not have permission to view this record.",
    "PropertyPanelFormMessages": "Form messages",
    "PropertyPanelPermissionDeniedMessage": "Permission denied message",
    "PropertyPanelPermissionDeniedMessageHint": "Shown when the current user cannot add, edit, or access the record based on the configured permission source.",
    "ValidationRequired": "{0} is required",
    "ValidationMinLength": "Minimum length is {0}",
    "ValidationMaxLength": "Maximum length is {0}",
    "ValidationMinValue": "Minimum value is {0}",
    "ValidationMaxValue": "Maximum value is {0}",
    "ValidationPattern": "Invalid format",
    "DesignerLoadFieldsFailed": "Failed to load fields",
    "DesignerNoListSelected": "No list selected",
    "DesignerStepNotFound": "Container not found",
    "DesignerAttachmentAlreadyExists": "Attachment field already exists",
    "DesignerStepDefaultTitle": "Container {0}",
    "DesignerAddStep": "+ Add container",
    "DesignerDeleteStep": "Delete container",
    "DesignerMoveStepLeft": "Move container left",
    "DesignerMoveStepRight": "Move container right",
    "DesignerMoveStepLeftLabel": "◀",
    "DesignerMoveStepRightLabel": "▶",
    "DesignerStepTitlePlaceholder": "Container title",
    "DesignerStepDescriptionPlaceholder": "Container description",
    "DesignerShowStep": "Show this container",
    "DesignerShowStepHelp": "When unchecked, this container is hidden by default and can be shown via other field logic.",
    "DesignerStepLayout": "Container layout",
    "DesignerLayoutStack": "Vertical stack",
    "DesignerLayoutGrid": "Grid layout",
    "DesignerColumns": "Columns",
    "DesignerColumnOption": "{0} columns",
    "DesignerRichTextChip": "Rich text",
    "DesignerColumnBadge": "{0} cols",
    "DesignerDelete": "Delete",
    "DesignerEdit": "Edit",
    "DesignerMoveUp": "Up",
    "DesignerMoveDown": "Down",
    "DesignerStartNewRow": "Start new row",
    "DesignerFormName": "Form name",
    "DesignerFieldPickerTitle": "Select a field to add",
    "DesignerFieldTypeAndInternal": "Type: {0} | Internal Name: {1}",
    "DesignerAddFieldTooltip": "Click to add field",
    "DesignerAddFieldHere": "+ Add field here",
    "DesignerClickAddField": "Click below to add fields",
    "DesignerAddFirstField": "+ Add first field",
    "DesignerRequiredFieldTitle": "Required",
    "DesignerPaletteListFields": "List fields",
    "DesignerCustomFields": "Custom fields",
    "DesignerCustomFieldsDesc": "Add fields via buttons on the right (not saved to SharePoint)",
    "DesignerSPFields": "SharePoint fields",
    "DesignerAddableFieldsCount": "Addable fields ({0})",
    "DesignerNoAddableFields": "No more fields available to add",
    "DesignerCustomRichTextTitle": "Rich text editor",
    "DesignerCustomRichTextDesc": "Use for instructions, notes, and rich content",
    "DesignerCustomListControlTitle": "List Control",
    "DesignerCustomListControlDesc": "Select a configured List Control web part on this page and show it at this position in the report.",
    "DesignerListControlSource": "List Control web part",
    "DesignerListControlNotSelected": "Select a List Control",
    "DesignerListControlUnavailable": "not currently available",
    "DesignerListControlRefresh": "Refresh List Controls",
    "DesignerListControlPreview": "Embedded List Control: {0}",
    "ListControlFieldWaiting": "Loading List Control: {0}",
    "ListControlFieldMissing": "List Control '{0}' was not found on this page.",
    "DesignerRichTextPlaceholder": "Enter rich text here...",
    "DesignerFieldTypeLabel": "{0} field",
    "PropertyPanelTitle": "Field properties",
    "PropertyPanelFieldInfo": "Field info",
    "PropertyPanelFieldName": "Name:",
    "PropertyPanelFieldType": "Type:",
    "PropertyPanelFieldInternalName": "Internal name:",
    "PropertyPanelFieldRequired": "Required:",
    "PropertyPanelFieldRequiredLocked": "Required (enforced by list — cannot be disabled)",
    "PropertyPanelFieldRequiredMessage": "Required message",
    "PropertyPanelFieldRequiredMessagePlaceholder": "Message shown when this field is empty",
    "PropertyPanelFieldEnabled": "Enabled",
    "PropertyPanelFieldEnabledHint": "When disabled, the field value and defaults are preserved, but users cannot change the control in Add or Edit mode.",
    "PropertyPanelFieldMaxLength": "Max length:",
    "PropertyPanelFieldChoices": "Choices:",
    "PropertyPanelFieldLookupList": "Lookup list:",
    "PropertyPanelColumnSpan": "Column span",
    "PropertyPanelColumnSpanDesc": "Set the number of columns this field occupies. Effective only in grid layout.",
    "PropertyPanelColumnSpanHint": "Example: In a 3-column layout, setting to 2 makes this field span 2 columns.",
    "PropertyPanelHelpText": "Field help text",
    "PropertyPanelHelpTextDesc": "Shown below the field to guide users.",
    "PropertyPanelHelpTextPlaceholder": "Example: Please enter full department name",
    "PropertyPanelDefaultsGroup": "Default values",
    "PropertyPanelDefaultsGroupDesc": "Applied when creating a new record (Add mode).",
    "PropertyPanelDefaultText": "Default text",
    "PropertyPanelDefaultTextPlaceholder": "Enter default text",
    "PropertyPanelDefaultNumber": "Default number",
    "PropertyPanelDefaultNumberPlaceholder": "Enter default number",
    "PropertyPanelDefaultDateTime": "Default date and time",
    "PropertyPanelDateFormat": "Date field format",
    "PropertyPanelDateFormatDateOnly": "Date only",
    "PropertyPanelDateFormatDateTime": "Date and time",
    "PropertyPanelDateFormatTimeOnly": "Time only",
    "PropertyPanelDateFormatCustom": "Custom",
    "PropertyPanelCustomDateFormatLabel": "Custom date/time format",
    "PropertyPanelCustomDateFormatDescription": "Tokens: YYYY, YY, MMMM, MMM, MM, M, DD, D, dddd, ddd, HH, H (24-hour), hh, h (12-hour), mm, ss, tt (AM/PM). Example: dddd, MMMM D, YYYY hh:mm tt",
    "PropertyPanelCustomDateFormatCaseLabel": "Text case",
    "PropertyPanelCustomDateFormatCaseDefault": "Default",
    "PropertyPanelCustomDateFormatCaseUpper": "UPPERCASE",
    "PropertyPanelCustomDateFormatCaseLower": "lowercase",
    "PropertyPanelTimeZone": "Time zone",
    "PropertyPanelTimeZoneUtc": "UTC (Zulu)",
    "PropertyPanelTimeZoneLocal": "Local browser time",
    "PropertyPanelDefaultBoolean": "Checked by default",
    "PropertyPanelBooleanText": "Checkbox text",
    "PropertyPanelBooleanTextPlaceholder": "Optional text beside the checkbox",
    "PropertyPanelBooleanTextHint": "Leave blank to show only the checkbox. This replaces the automatic Yes/No text.",
    "PropertyPanelDefaultChoice": "Default choice (Add mode)",
    "PropertyPanelDefaultChoiceEmpty": "No choices available for this field.",
    "PropertyPanelDefaultMultiSelect": "Default selections (Add mode)",
    "PropertyPanelDefaultMultiSelectPlaceholder": "Value A; Value B",
    "PropertyPanelDefaultMultiSelectHint": "Use semicolons to separate multiple default values.",
    "PropertyPanelDefaultLookupId": "Default lookup item ID (Add mode)",
    "PropertyPanelDefaultLookupIdPlaceholder": "Enter lookup item ID, e.g. 1",
    "PropertyPanelDefaultLookupIdHint": "Use the target list item ID to preselect the lookup value when creating a new record.",
    "PropertyPanelAttachmentAllowDelete": "Allow deleting existing attachments",
    "PropertyPanelAttachmentAllowDeleteHint": "When disabled, existing attachments are shown read-only and cannot be marked for deletion.",
    "PropertyPanelDefaultUnsupportedHint": "Default value is not supported for this field type yet.",
    "PropertyPanelDefaultNone": "None",
    "PropertyPanelRichTextContent": "Rich text content",
    "PropertyPanelRichTextDesc": "Edit rich text content shown in the form.",
    "PropertyPanelMissingSPField": "SP field info not found. Some settings may not display correctly.",
    "PropertyFieldTypeText": "Single line text",
    "PropertyFieldTypeMultiline": "Multiple lines of text",
    "PropertyFieldTypeNumber": "Number",
    "PropertyFieldTypeDatetime": "Date and time",
    "PropertyFieldTypeDropdown": "Dropdown",
    "PropertyFieldTypeMultiselect": "Multi-select",
    "PropertyFieldTypeLookup": "Lookup",
    "PropertyFieldTypePerson": "Person",
    "PropertyFieldTypeBoolean": "Yes/No",
    "PropertyFieldTypeImage": "Image",
    "PropertyFieldTypeUrl": "Hyperlink",
    "PropertyFieldTypeTaxonomy": "Managed metadata",
    "PropertyFieldTypeAttachment": "Attachment",
    "PropertyFieldTypeRichtext": "Rich text",
    "PropertyFieldTypeListControl": "List Control",
    "ConditionOpEq": "equals",
    "ConditionOpNe": "not equals",
    "ConditionOpGt": "greater than",
    "ConditionOpGe": "greater than or equal",
    "ConditionOpLt": "less than",
    "ConditionOpLe": "less than or equal",
    "ConditionOpContains": "contains",
    "ConditionOpStartsWith": "starts with",
    "ConditionVisibilityLabel": "Visibility condition",
    "ConditionVisibilityDesc": "Set when this field is shown. Leave empty to always show.",
    "ConditionNoRules": "No conditions set. Field will always be visible.",
    "ConditionRuleLabel": "Condition {0}",
    "ConditionFieldLabel": "Field",
    "ConditionFieldPlaceholder": "Select field",
    "ConditionOperatorLabel": "Operator",
    "ConditionValueLabel": "Value",
    "ConditionValuePlaceholder": "Enter comparison value",
    "ConditionAnd": "AND",
    "ConditionAdd": "+ Add condition",
    "ConditionHint": "Tip: Conditions are combined with AND. For example: Department equals \"IT\" AND Status not equals \"Closed\".",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  }
});
