/// <reference types="react" />
import * as React from 'react';
import './ListControl.css';
export interface IListControlViewOption {
    key: string;
    text: string;
    isDefault?: boolean;
}
export interface IListControlColumnConfiguration {
    fieldName: string;
    displayName: string;
    width?: string;
}
export interface IListControlProps {
    context: any;
    listName: string;
    defaultViewId: string;
    views: IListControlViewOption[];
    viewColumns: IListControlColumnConfiguration[];
    groupingJson?: string;
    pageSize: number;
    fetchBatchSize: number;
    isEditMode: boolean;
    showViewSelector: boolean;
    showViewAsDropdown: boolean;
    showRefresh: boolean;
    showAdd: boolean;
    showEdit: boolean;
    showView: boolean;
    showDelete: boolean;
    showLinkToItem: boolean;
    linkOpenBehavior: string;
    linkTargetPageUrl: string;
    linkTargetIdParam: string;
    includeReturnUrlParam: boolean;
    enableDiagnostics: boolean;
    bodyTextColor: string;
    bodyFontFamily: string;
    bodyFontSize: string;
    bodyFontStyle: string;
    bodyFontBold: boolean;
    bodyTextAlign: string;
    dateDisplayFormat: string;
    dateCustomFormat?: string;
    dateCustomFormatCase?: string;
    timeDisplayFormat: string;
    timeCustomFormat?: string;
    timeCustomFormatCase?: string;
    selectedTextColor: string;
    selectedBackgroundColor: string;
    selectedFontStyle: string;
    selectedFontBold: boolean;
    headerTextColor: string;
    headerBackgroundColor: string;
    headerFontFamily: string;
    headerFontSize: string;
    headerFontStyle: string;
    headerFontBold: boolean;
    headerTextAlign: string;
    tableBackgroundColor: string;
    tableBorderColor: string;
    tableBorderWidth: string;
    tableCornerStyle: string;
    tableCornerRadius: number;
    tableRowLineWidth: number;
    cornerStyle: string;
    cornerRadius: number;
    alternateRowShading: boolean;
    alternateRowShadingColor: string;
    buttonTextColor: string;
    buttonBackgroundColor: string;
    buttonFontFamily: string;
    buttonFontSize: string;
    buttonFontStyle: string;
    buttonFontBold: boolean;
    buttonCornerStyle: string;
    buttonCornerRadius: number;
    buttonDisplayMode: string;
    webpartBackgroundColor: string;
    webpartBorderColor: string;
    webpartBorderWidth: number;
    filterJson?: string;
    conditionalStyleJson?: string;
    onSelectionChange: (itemId: number, mode: string) => void;
}
export interface IListFieldDefinition {
    Name: string;
    RealFieldName?: string;
    DisplayName?: string;
    TypeAsString?: string;
    DisplayFormat?: number;
    Hidden?: string | boolean;
    ConfiguredWidth?: string;
    RuntimeFilterOnly?: boolean;
}
export interface IListControlState {
    selectedViewId: string;
    fields: IListFieldDefinition[];
    rows: any[];
    loading: boolean;
    loadingMore: boolean;
    nextPageHref: string;
    error: string | null;
    selectedItemId: number;
    selectedMode: string;
    deleting: boolean;
    sortFieldName: string;
    sortDirection: 'asc' | 'desc' | '';
    activeFilterFieldName: string;
    filterPopoverStyle: any;
    activeFilterIsDate: boolean;
    draftFilterOperator: FilterOperator;
    draftFilterValue: string;
    draftFilterEndValue: string;
    datePickerTarget: 'start' | 'end' | '';
    datePickerMonth: string;
    columnFilters: {
        [fieldName: string]: IColumnFilter;
    };
    currentPage: number;
    collapsedGroupKeys: {
        [groupKey: string]: boolean;
    };
    displayFormUrl: string;
    displayFormLoading: boolean;
    displayFormError: string;
    embeddedByReportForms: boolean;
    runtimeFilterJson: string;
    runtimeConfigOwner: string;
    attachmentCountsByItemId: {
        [itemId: number]: number;
    };
    showScrollArrows: boolean;
    scrollArrowTop: number;
    scrollArrowLeft: number;
    scrollArrowRight: number;
}
export declare type FilterOperator = 'eq' | 'ne' | 'contains' | 'notcontains' | 'startswith' | 'endswith' | 'gt' | 'ge' | 'lt' | 'le';
export interface IColumnFilter {
    operator: FilterOperator;
    value: any;
    endValue?: string;
    compareDateOnly?: boolean;
}
export declare class ListControl extends React.Component<IListControlProps, IListControlState> {
    private _refreshEventHandler;
    private _runtimeConfigEventHandler;
    private _fieldDisplayFormatMap;
    private _loadRowsRequestId;
    private _tableWrapEl;
    private _tableHeadEl;
    private _stickyHeaderViewportEl;
    private _stickyHeaderSourceHtml;
    private _stickyHeaderVisible;
    private _filterAnchorEl;
    private _pagingEndpoint;
    private _pagingRequestBody;
    private _pagingRuntimeFilterFieldNames;
    private _scrollArrowResizeHandler;
    private _scrollArrowScrollHandler;
    constructor(props: IListControlProps);
    componentDidMount(): void;
    componentWillUnmount(): void;
    private openItemLinkDialog(itemLinkUrl);
    private openItemLinkWindow(itemLinkUrl);
    private closeDefaultDisplayForm();
    private setDisplayFormFrameRef;
    componentDidUpdate(prevProps: IListControlProps, prevState: IListControlState): void;
    private _setTableWrapRef;
    private _setTableHeadRef;
    private _setStickyHeaderViewportRef;
    private handleStickyHeaderClick;
    private getStickyHeaderControls(root);
    private refreshTableViewport();
    private refreshScrollArrows();
    private updateScrollArrowVisibility();
    private updateScrollArrowPosition();
    private updateStickyHeaderPosition();
    private getStickyViewportTop(wrapRect);
    private getScrollViewportTop(viewportHeight);
    private scrollTableHorizontally(direction);
    private getInitialViewId(views);
    private getSelectedViewLabel();
    private handleExternalRefresh(event);
    private handleRuntimeConfig(event);
    private getWebUrl();
    private getJsonWithFallback(url);
    private postJsonWithFallback(url, body);
    private buildViewIdCandidates(selectedViewId);
    private buildMinimalViewXml(viewQuery, viewFieldNames, rowLimit, scope);
    private addFieldsToViewXml(viewXml, fieldNames);
    private loadSelectedViewXml(selectedViewId, viewFieldNames);
    private loadSelectedViewFieldNames(selectedViewId);
    private getDisplayFields();
    private getConfiguredColumnStyle(field);
    private getFieldsForConsumption(rawFields, viewFieldNames);
    private loadListFieldTypeMap(viewFieldNames);
    private loadListFieldTitleMap();
    private applyFieldDisplayNames(fields, titleMap);
    private applyFieldTypes(fields, typeMap);
    private getRowFieldValue(row, field);
    private getUrlCellValue(row, field);
    private stringifyCellValue(value);
    private formatDateCellValue(value, field, row?);
    private isMeaningfulCellValue(value);
    private filterRenderableRows(rows, visibleFields);
    private loadRowsFromItemsEndpoint(viewFieldNames, itemIds?);
    private getRuntimeFilterFieldNames();
    private mergeHydratedRows(rows, hydratedRows);
    private loadAttachmentCounts(itemIds);
    private loadRows();
    private applyFetchBatchSize(viewXml);
    private loadNextBatch();
    private loadAllRemainingRows();
    private goToNextPage(currentPage, pageCount);
    private getRowItemId(row);
    private selectRow(row);
    private deleteSelected();
    private logDiagnostic(message);
    private getCellMarkup(row, field);
    private isTitleField(field);
    private getCellPlainText(row, field);
    private getAttachmentCountForRow(row, rawAttachmentsValue);
    private getItemLinkUrl(row);
    private getFieldKey(field);
    private getFilterOperatorOptions();
    private toggleSort(field);
    private openFilter(field, anchorElement);
    private getFilterPopoverStyle(anchorElement);
    private updateActiveFilterPosition();
    private closeFilter();
    private getIsoDate(date);
    private toggleDatePicker(target);
    private changeDatePickerMonth(offset);
    private selectFilterDate(value);
    private renderDatePicker();
    private applyActiveFilter();
    private clearActiveFilter();
    private compareComparableValues(leftValue, rightValue);
    private rowMatchesFilter(row, field, filter);
    private getFilterCellText(row, field);
    private parsePresetFilterConditions();
    private resolveFieldByReference(fieldsByKey, fieldRef);
    private rowMatchesPresetConditions(row, fieldsByKey, conditions);
    private resolvePresetFilterValue(condition);
    private getProcessedRows();
    private getGroupingConfig();
    private resolveFieldDefinitionByName(fieldName);
    private getGroupValueText(row, fieldName);
    private buildRowGroups(rows, grouping);
    private countGroupRows(group);
    private isGroupCollapsed(groupKey, collapsedByDefault);
    private toggleGroupCollapsed(groupKey, collapsedByDefault);
    private parseConditionalStyleRules();
    private toReactCssStyle(styleDefinition);
    private evaluateConditionalStyleRule(row, rule, fieldsByKey);
    private getConditionalStyleForRow(row, fieldsByKey, rules);
    private getMatchedConditionalRuleNames(row, fieldsByKey, rules);
    private getCommandButtonClass(className?);
    private renderCommandContent(iconName, label);
    private renderDataRow(row, keySuffix, displayFields, fieldsByKey, conditionalRules);
    private renderGroupHeaderRow(group, keyPath, level, totalColumnCount, groupingConfig);
    private renderRowGroupRows(group, keyPath, level, groupingConfig, totalColumnCount, displayFields, fieldsByKey, conditionalRules);
    render(): JSX.Element;
}
