import { Version } from '@microsoft/sp-core-library';
import { BaseClientSideWebPart, IPropertyPaneConfiguration } from '@microsoft/sp-webpart-base';
import { IListControlColumnConfiguration } from './components/ListControl';
export interface IDynamicDataPropertyDefinitionCompat {
    id: string;
    title: string;
    description?: string;
}
export interface IDynamicDataSourceMetadataCompat {
    title: string;
    description?: string;
    alias?: string;
    componentId?: string;
    instanceId?: string;
}
export interface IListControlWebPartProps {
    forceFullWidth?: boolean;
    description: string;
    instanceName?: string;
    listName: string;
    viewId: string;
    viewColumns?: IListControlColumnConfiguration[];
    pageSize?: number | string;
    showViewSelector: boolean;
    showRefresh: boolean;
    showAdd: boolean;
    showEdit: boolean;
    showView: boolean;
    showDelete: boolean;
    showLinkToItem: boolean;
    linkTargetPageUrl: string;
    linkTargetIdParam: string;
    includeReturnUrlParam: boolean;
    enableDiagnostics: boolean;
    bodyTextColor: string;
    bodyFontFamily: string;
    bodyFontSize: string;
    bodyFontStyle: string;
    bodyFontBold: boolean;
    bodyTextAlign: string;
    dateDisplayFormat: string;
    timeDisplayFormat: string;
    selectedTextColor: string;
    selectedBackgroundColor: string;
    selectedFontStyle: string;
    selectedFontBold: boolean;
    headerTextColor: string;
    headerBackgroundColor: string;
    headerFontFamily: string;
    headerFontSize: string;
    headerFontStyle: string;
    headerFontBold: boolean;
    headerTextAlign: string;
    tableBackgroundColor: string;
    tableBorderColor: string;
    tableBorderWidth: string;
    tableCornerStyle: string;
    tableCornerRadius: number;
    tableRowLineWidth: number;
    cornerStyle: string;
    cornerRadius: number;
    alternateRowShading: boolean;
    alternateRowShadingColor: string;
    buttonTextColor: string;
    buttonBackgroundColor: string;
    buttonFontFamily: string;
    buttonFontSize: string;
    buttonFontStyle: string;
    buttonFontBold: boolean;
    buttonCornerStyle: string;
    buttonCornerRadius: number;
    webpartBackgroundColor: string;
    webpartBorderColor: string;
    webpartBorderWidth: number;
    filterJson?: string;
    filterDesignerField?: string;
    filterDesignerOperator?: 'eq' | 'ne' | 'gt' | 'ge' | 'lt' | 'le' | 'contains' | 'startswith' | 'endswith' | 'notcontains';
    filterDesignerLogical?: 'and' | 'or';
    filterDesignerValueType?: 'static' | 'expression' | 'fieldValue';
    filterDesignerValue?: string;
    filterDesignerSelectedIndex?: string;
    filterDesignerLookupPick?: string;
    conditionalStyleJson?: string;
    conditionalStyleRuleName?: string;
    conditionalStyleScope?: 'row' | 'column';
    conditionalStyleApplyField?: string;
    conditionalStyleConditionField?: string;
    conditionalStyleConditionOperator?: 'eq' | 'ne' | 'gt' | 'ge' | 'lt' | 'le' | 'contains' | 'startswith' | 'endswith' | 'notcontains';
    conditionalStyleConditionLogical?: 'and' | 'or';
    conditionalStyleConditionValueType?: 'static' | 'expression';
    conditionalStyleConditionValue?: string;
    conditionalStyleEnabled?: boolean;
    conditionalStylePriority?: string;
    conditionalStyleBackgroundColor?: string;
    conditionalStyleForegroundColor?: string;
    conditionalStyleFontFamily?: string;
    conditionalStyleFontSize?: string;
    conditionalStyleFontStyle?: string;
    conditionalStyleFontWeight?: string;
    conditionalStyleTextAlign?: string;
    conditionalStyleSelectedIndex?: string;
    conditionalStyleLookupPick?: string;
}
export interface IDropdownOption {
    key: string | number;
    text: string;
}
export default class ListControlWebPart extends BaseClientSideWebPart<IListControlWebPartProps> {
    private _lists;
    private _sitePages;
    private _views;
    private _listFields;
    private _selectedItemId;
    private _selectedMode;
    private _dynamicDataSourceManager;
    private _filterJsonValidationMessage;
    private _filterDesignerMessage;
    private _showFilterExpressionHelp;
    private _conditionalStyleJsonValidationMessage;
    private _conditionalStyleDesignerMessage;
    private _showConditionalStyleExpressionHelp;
    private _isEditingConditionalStyle;
    private _conditionalStyleDesignerRevision;
    private _fieldTypeByInternalName;
    private _fieldChoicesByInternalName;
    private _fieldLookupListByInternalName;
    private _filterLookupItemOptions;
    private _conditionalStyleLookupItemOptions;
    private _filterLookupMessage;
    private _conditionalStyleLookupMessage;
    constructor();
    readonly id: string;
    readonly metadata: IDynamicDataSourceMetadataCompat;
    getPropertyDefinitions(): ReadonlyArray<IDynamicDataPropertyDefinitionCompat>;
    getPropertyValue(propertyId: string): any;
    render(): void;
    protected onInit(): Promise<void>;
    protected onPropertyPaneConfigurationStart(): void;
    protected onPropertyPaneFieldChanged(propertyPath: string, oldValue: any, newValue: any): void;
    private loadListFields(listName);
    private isLookupTypeField(internalName);
    private supportsFilterFieldValue(internalName);
    private isMultiFilterField(internalName);
    private getSelectedFilterFieldValues();
    private createFilterMultiValuePicker(options);
    private loadLookupListItems(listId);
    private handleLoadFilterLookupItems();
    private handleApplyFilterLookupPick();
    private handleLoadConditionalStyleLookupItems();
    private handleApplyConditionalStyleLookupPick();
    private createPropertyPanePageTitle(key, title);
    private createFilterExpressionHelpField();
    private createConditionalStyleExpressionHelpField();
    private handleColorPropertyChange(propertyPath, oldValue, newValue);
    protected onDispose(): void;
    protected readonly dataVersion: Version;
    protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration;
    private getWebPartVersion();
    private getFontFamilyOptions();
    private getFontStyleOptions();
    private getTextAlignOptions();
    private validateJsonText(raw, expectedShape);
    private parseFilterJsonArray(raw);
    private handleValidateFilterJson();
    private handleAddFilterDesignerCondition();
    private handleLoadSelectedFilterCondition();
    private handleUpdateSelectedFilterCondition();
    private handleRemoveSelectedFilterCondition();
    private handleResetFilterJson();
    private isSupportedFilterExpression(value);
    private parseConditionalStyleJsonArray(raw);
    private handleValidateConditionalStyleJson();
    private parseConditionalStylePriority(raw);
    private createConditionalStyleEntryFromDesigner();
    private resetConditionalStyleDesigner();
    private handleNewConditionalStyle();
    private handleAddConditionalStyleCondition();
    private handleLoadSelectedConditionalStyleCondition();
    private handleUpdateSelectedConditionalStyleCondition();
    private handleRemoveSelectedConditionalStyleCondition();
    private handleMoveConditionalStyleConditionUp();
    private handleMoveConditionalStyleConditionDown();
    private handleResetConditionalStyleJson();
    private initializeDynamicDataSource();
    private notifyDynamicSourceChanged();
    private notifyDynamicData(propertyId);
    private handleSelectionChange(itemId, mode);
    private getJsonWithAcceptFallback(url);
    private loadLists();
    private getTargetPageOptions();
    private loadSitePages();
    private loadViews(listName);
    private loadViewColumns(listName, viewId);
    private logDiagnostic(message);
}
