define([], function() {
  return {
    "PropertyPaneDescription": "SPS Calendar",
    "BasicGroupName": "Basic",
    "TitleFieldLabel": "Title",
    "DescriptionFieldLabel": "Description",

    "DataSourceGroupName": "Data Source",
    "ListNameFieldLabel": "Events list",
    "DataSourcesCollectionLabel": "Calendar data sources",
    "DataSourcesCollectionHeader": "Calendar data sources",
    "DataSourcesCollectionDescription": "Add Events lists or lists with calendar views. Set optional hex background and text colors for each source; conditional styles and selected-event colors can override them.",
    "DataSourcesCollectionManageButton": "Manage data sources",
    "DataSourceListLabel": "Calendar source list",
    "DataSourceTargetPageLabel": "Target page",
    "DataSourceDefaultFormOption": "Display List Default Form",
    "DataSourceEventsDateFieldsOption": "Defaults",
    "DataSourceEventsListType": "Events list",
    "DataSourceCalendarViewListType": "calendar view",
    "DataSourceRuleScopeLabel": "Apply to data source",
    "DataSourceAllOption": "All data sources",
    "DataSourceAllShortLabel": "All sources",
    "DataSourceStartFieldLabel": "Start date column",
    "DataSourceEndFieldLabel": "End date column",
    "DataSourceBackgroundColorLabel": "Event background color",
    "DataSourceLegendButtonLabel": "Data source legend",
    "DataSourceLegendTitle": "Event data sources",
    "DefaultViewFieldLabel": "Default view",
    "ViewMonthLabel": "Month",
    "ViewWeekLabel": "Week",
    "ViewDayLabel": "Day",
    "ViewListLabel": "List",
    "ShowWeekendsFieldLabel": "Show weekends",
    "CalendarHeightFieldLabel": "Calendar height (px)",
    "EnableSwimlanesLabel": "Use swim lanes",
    "SwimlaneFieldLabel": "Group lanes by field",
    "SwimlaneFieldNone": "Select a field",
    "SwimlaneDaysLabel": "Visible day range",
    "SwimlaneDaysSeven": "7 days",
    "SwimlaneDaysFourteen": "14 days",
    "SwimlaneDaysThirty": "30 days",
    "SwimlaneUnassignedLabel": "Empty-value lane label",
    "SwimlaneUnassignedDefault": "Unassigned",
    "SwimlaneSelectFieldMessage": "Select a grouping field in the web part properties to display swim lanes.",
    "SwimlanePreviousLabel": "Previous date range",
    "SwimlaneTodayLabel": "Today",
    "SwimlaneNextLabel": "Next date range",
    "SwimlaneLaneLabel": "Lane",
    "SwimlaneNoEventsMessage": "No events match this date range and filter.",
    "FilterJsonLabel": "Event filter JSON",
    "FilterJsonDescription": "Array of conditions using sourceListName, field, operator, logical, and value. Blank sourceListName applies to all data sources.",
    "FilterPageDescription": "Build event filters for all data sources or a selected source list.",
    "FilterSummaryGroupName": "Filter summary",
    "FilterDesignerGroupName": "Event filter designer",
    "FilterJsonGroupName": "Filter JSON",
    "FilterSummaryNone": "No event filters configured.",
    "FilterSummaryInvalid": "The filter JSON is invalid.",
    "FilterSummaryConditionsLabel": "filter conditions",
    "FilterDesignerFieldLabel": "Filter field",
    "FilterDesignerFieldNone": "Select a field",
    "FilterDesignerOperatorLabel": "Filter operator",
    "FilterDesignerLogicalLabel": "Logical join",
    "FilterDesignerValueTypeLabel": "Value type",
    "FilterDesignerValueLabel": "Filter value",
    "FilterDesignerValuePlaceholder": "Enter a value",
    "FilterDesignerAddButton": "Add condition to JSON",
    "FilterDesignerExistingLabel": "Existing filter conditions",
    "FilterDesignerExistingNone": "No filter conditions in JSON",
    "FilterDesignerLoadButton": "Load selected condition",
    "FilterDesignerUpdateButton": "Update selected condition",
    "FilterDesignerRemoveButton": "Remove selected condition",
    "FilterDesignerResetButton": "Clear filter JSON",
    "FilterDesignerStatusPlaceholder": "Filter designer result appears here.",
    "FilterJsonPlaceholder": "[{\"field\":\"Category\",\"operator\":\"eq\",\"logical\":\"and\",\"valueType\":\"static\",\"value\":\"Meeting\"}]",
    "FilterValidateButton": "Validate filter JSON",
    "FilterValidationPlaceholder": "Validation result appears here.",
    "FilterDesignerFieldRequired": "Select a filter field before adding or updating.",
    "FilterDesignerValueRequired": "Enter a filter value before adding or updating.",
    "FilterDesignerSelectValid": "Select a valid filter condition first.",
    "FilterDesignerAddSuccess": "Filter condition added.",
    "FilterDesignerLoadSuccess": "Filter condition loaded.",
    "FilterDesignerUpdateSuccess": "Filter condition updated.",
    "FilterDesignerRemoveSuccess": "Filter condition removed.",
    "FilterDesignerResetSuccess": "Filter JSON cleared.",
    "FilterDesignerActionFailed": "Failed to process the filter action.",
    "LookupPickerHelp": "Lookup item picker: choose an item from the target list to fill the filter value.",
    "LookupRefreshButton": "Refresh lookup items",
    "LookupSelectLabel": "Select item",
    "LookupItemsNotLoaded": "No items loaded yet",
    "LookupApplyButton": "Use selected value",
    "LookupStatusPlaceholder": "Lookup items load automatically when a lookup field is selected.",
    "LookupItemNoTitle": "(no title)",
    "LookupFieldUnavailable": "The selected field is not a lookup field, or its target list could not be resolved.",
    "LookupItemsLoaded": "lookup item(s) loaded. Pick one and use the selected value.",
    "LookupItemsEmpty": "The target list has no items.",
    "LookupSelectFirst": "Select an item before applying it.",
    "LookupValueApplied": "The selected lookup value was applied.",

    "LinkGroupName": "Event links",
    "EnableEventDetailsLabel": "Show an expanding event details panel",
    "EventDetailsCollectionLabel": "Event details fields",
    "EventDetailsCollectionHeader": "Configure event details fields",
    "EventDetailsCollectionDescription": "Add fields, drag rows to control their order, and configure how each value is displayed.",
    "EventDetailsCollectionManageButton": "Manage details fields",
    "EventDetailsSourceAndFieldLabel": "Data source / details field",
    "EventDetailsSourceLabel": "Data source",
    "EventDetailsFieldLabel": "Details field",
    "EventDetailsSelectFieldOption": "Select a field",
    "EventDetailsLabelLabel": "Display label",
    "EventDetailsShowLabelLabel": "Show label",
    "EventDetailsFormatLabel": "Value format",
    "EventDetailsFormatAuto": "Automatic",
    "EventDetailsFormatText": "Text",
    "EventDetailsFormatDate": "Date",
    "EventDetailsFormatDateTime": "Date and time",
    "EventDetailsFormatTime": "Time",
    "EventDetailsFormatYesNo": "Yes/No",
    "EventDetailsHideEmptyLabel": "Hide when empty",
    "RecurrenceDetailsLabel": "Repeats",
    "RecurringEventFallback": "Recurring event",
    "ShowLinkToItemLabel": "Open the selected event",
    "DetailsLinkPresentationLabel": "Event details link appearance",
    "DetailsLinkPresentationButton": "Open event button",
    "DetailsLinkPresentationTitle": "Linked event title",
    "OpenEventDetailsButton": "Open event",
    "LinkTargetPageUrlLabel": "Target page URL (blank uses the default display form)",
    "LinkTargetIdParamLabel": "Item ID query parameter",
    "IncludeReturnUrlParamLabel": "Include the current page as the return parameter",

    "AppearanceGroupName": "Appearance and rules",
    "AppearanceDefaultLabel": "Default",
    "AppearancePageDescription": "Control the calendar surface, headings, toolbar buttons, and events independently.",
    "CalendarSurfaceGroupName": "Calendar surface",
    "WebPartTitleAppearanceGroupName": "Web part header",
    "CalendarTitleAppearanceGroupName": "Calendar date title",
    "ToolbarButtonAppearanceGroupName": "Toolbar buttons",
    "EventAppearanceGroupName": "Events",
    "SelectedEventAppearanceGroupName": "Selected event",
    "EventDetailsAppearanceGroupName": "Event details panel",
    "CalendarBackgroundColorLabel": "Calendar background color",
    "WebPartBorderColorLabel": "Web part border color",
    "WebPartBorderWidthLabel": "Web part border width (px)",
    "WebPartCornerRadiusLabel": "Web part corner radius (px)",
    "TitleTextColorLabel": "Text color",
    "TitleBackgroundColorLabel": "Header background color",
    "TitleFontFamilyLabel": "Font family",
    "TitleFontSizeLabel": "Font size",
    "TitleFontStyleLabel": "Font style",
    "TitleFontBoldLabel": "Bold title text",
    "TitleAlignmentLabel": "Alignment",
    "AlignmentLeft": "Left",
    "AlignmentCenter": "Center",
    "AlignmentRight": "Right",
    "TitleMinHeightLabel": "Minimum header height (px, 0 is automatic)",
    "DescriptionTextColorLabel": "Description text color",
    "DescriptionFontFamilyLabel": "Description font family",
    "DescriptionFontSizeLabel": "Description font size",
    "DescriptionFontStyleLabel": "Description font style",
    "DescriptionFontBoldLabel": "Bold description text",
    "ToolbarButtonBackgroundColorLabel": "Button background color",
    "ToolbarButtonTextColorLabel": "Button text color",
    "ToolbarButtonBorderColorLabel": "Button border color",
    "ToolbarButtonActiveBackgroundColorLabel": "Selected button background color",
    "ToolbarButtonActiveTextColorLabel": "Selected button text color",
    "ToolbarButtonFontFamilyLabel": "Button font family",
    "ToolbarButtonFontSizeLabel": "Button font size",
    "ToolbarButtonFontStyleLabel": "Button font style",
    "ToolbarButtonFontBoldLabel": "Bold button text",
    "ToolbarButtonBorderWidthLabel": "Button border width (px)",
    "ToolbarButtonCornerRadiusLabel": "Button corner radius (px)",
    "EventBackgroundColorLabel": "Event background color",
    "EventTextColorLabel": "Event text color",
    "EventBorderColorLabel": "Event border color",
    "EventFontFamilyLabel": "Event font family",
    "EventFontSizeLabel": "Event font size",
    "EventFontStyleLabel": "Event font style",
    "EventFontBoldLabel": "Bold event text",
    "EventBorderWidthLabel": "Event border width (px)",
    "EventCornerRadiusLabel": "Event corner radius (px)",
    "SelectedEventBackgroundColorLabel": "Selected event background color",
    "SelectedEventTextColorLabel": "Selected event text color",
    "SelectedEventBorderColorLabel": "Selected event border color",
    "SelectedEventFontFamilyLabel": "Selected event font family",
    "SelectedEventFontSizeLabel": "Selected event font size",
    "SelectedEventFontStyleLabel": "Selected event font style",
    "SelectedEventFontBoldLabel": "Bold selected event text",
    "SelectedEventBorderWidthLabel": "Selected event border width (px)",
    "SelectedEventCornerRadiusLabel": "Selected event corner radius (px)",
    "DetailsOverlayColorLabel": "Overlay color",
    "DetailsOverlayOpacityLabel": "Overlay opacity (%)",
    "DetailsPanelBackgroundColorLabel": "Panel background color",
    "DetailsPanelBorderColorLabel": "Panel border color",
    "DetailsPanelBorderWidthLabel": "Panel border width (px)",
    "DetailsPanelCornerRadiusLabel": "Panel corner radius (px)",
    "DetailsPanelMaxWidthLabel": "Panel maximum width (px)",
    "DetailsPanelPaddingLabel": "Panel padding (px)",
    "DetailsPanelShadowLabel": "Show panel shadow",
    "DetailsTitleTextColorLabel": "Title text color",
    "DetailsTitleFontFamilyLabel": "Title font family",
    "DetailsTitleFontSizeLabel": "Title font size",
    "DetailsTitleFontStyleLabel": "Title font style",
    "DetailsTitleFontBoldLabel": "Bold title",
    "DetailsLabelTextColorLabel": "Field label text color",
    "DetailsLabelFontFamilyLabel": "Field label font family",
    "DetailsLabelFontSizeLabel": "Field label font size",
    "DetailsLabelFontStyleLabel": "Field label font style",
    "DetailsLabelFontBoldLabel": "Bold field labels",
    "DetailsValueTextColorLabel": "Field value text color",
    "DetailsValueFontFamilyLabel": "Field value font family",
    "DetailsValueFontSizeLabel": "Field value font size",
    "DetailsValueFontStyleLabel": "Field value font style",
    "DetailsValueFontBoldLabel": "Bold field values",
    "DetailsDividerColorLabel": "Row divider color",
    "DetailsDividerWidthLabel": "Row divider width (px)",
    "DetailsCloseButtonColorLabel": "Close icon color",
    "DetailsCloseButtonBackgroundColorLabel": "Close button background",
    "DetailsCloseButtonHoverBackgroundColorLabel": "Close button hover background",
    "DetailsCloseButtonCornerRadiusLabel": "Close button corner radius (px)",
    "ConditionalStyleJsonLabel": "Conditional event style JSON",
    "ConditionalStyleJsonDescription": "Rules contain conditions plus style values such as backgroundColor, textColor, borderColor, fontFamily, fontSize, fontStyle, and fontWeight.",
    "ConditionalStylePageDescription": "Build conditional event styles for all data sources or a selected source list.",
    "ConditionalStyleSummaryGroupName": "Rule summary",
    "ConditionalStyleDesignerGroupName": "Conditional event style designer",
    "ConditionalStyleJsonGroupName": "Conditional style JSON",
    "ConditionalStyleFieldNone": "Select a field",
    "ConditionalStyleSummaryNone": "No conditional event styles configured.",
    "ConditionalStyleSummaryInvalid": "The conditional style JSON is invalid.",
    "ConditionalStyleUnnamedRule": "Unnamed rule",
    "ConditionalStyleRulesLabel": "rules",
    "ConditionalStyleConditionsLabel": "conditions",
    "ConditionalStyleRuleNameLabel": "Rule name",
    "ConditionalStyleRuleNamePlaceholder": "Example: HolidayEvents",
    "ConditionalStyleConditionFieldLabel": "Condition field",
    "ConditionalStyleOperatorLabel": "Condition operator",
    "ConditionalStyleLogicalLabel": "Logical join",
    "ConditionalStyleValueTypeLabel": "Value type",
    "ConditionalStyleValueTypeStatic": "Static value",
    "ConditionalStyleValueTypeExpression": "Expression",
    "ConditionalStyleValueLabel": "Condition value",
    "ConditionalStyleValuePlaceholder": "Enter a value",
    "ConditionalStyleExpressionPlaceholder": "today, now, date(7), or me.email",
    "ConditionalStyleExpressionHelp": "Supported expressions: today, now, date(n), me, me.email, me.login, me.id, and me.title.",
    "ConditionalStyleEnabledLabel": "Enable this rule",
    "ConditionalStylePriorityLabel": "Priority (higher values apply later)",
    "ConditionalStyleBackgroundColorLabel": "Event background color",
    "ConditionalStyleBorderColorLabel": "Event border color",
    "ConditionalStyleTextColorLabel": "Event text color",
    "ConditionalStyleFontFamilyLabel": "Event font family",
    "ConditionalStyleFontSizeLabel": "Event font size",
    "ConditionalStyleFontStyleLabel": "Event font style",
    "ConditionalStyleFontWeightLabel": "Event font weight",
    "ConditionalStyleDefault": "Default",
    "ConditionalStyleAddButton": "Add condition to JSON",
    "ConditionalStyleNewButton": "New style",
    "ConditionalStyleExistingLabel": "Existing conditions",
    "ConditionalStyleExistingNone": "No conditions in JSON",
    "ConditionalStyleLoadButton": "Load selected condition",
    "ConditionalStyleUpdateButton": "Update selected condition",
    "ConditionalStyleRemoveButton": "Remove selected condition",
    "ConditionalStyleMoveUpButton": "Move selected condition up",
    "ConditionalStyleMoveDownButton": "Move selected condition down",
    "ConditionalStyleResetButton": "Clear conditional style JSON",
    "ConditionalStyleStatusPlaceholder": "Designer result appears here.",
    "ConditionalStyleJsonPlaceholder": "[{\"rule\":\"HolidayEvents\",\"conditionField\":\"Category\",\"operator\":\"eq\",\"logical\":\"and\",\"value\":\"Holiday\",\"style\":{\"backgroundColor\":\"#a4262c\",\"textColor\":\"#ffffff\"}}]",
    "ConditionalStyleValidateButton": "Validate conditional style JSON",
    "ConditionalStyleValidationPlaceholder": "Validation result appears here.",
    "JsonValidationExpectedArray": "JSON must be an array.",
    "JsonValidationSuccess": "JSON is valid.",
    "JsonValidationEmpty": "Empty value is allowed.",
    "ConditionalStyleRuleNameRequired": "Enter a rule name before adding or updating a condition.",
    "ConditionalStyleFieldRequired": "Select a condition field before adding or updating.",
    "ConditionalStyleValueRequired": "Enter a condition value before adding or updating.",
    "ConditionalStyleExpressionInvalid": "Enter a supported expression.",
    "ConditionalStyleSelectValid": "Select a valid conditional style condition first.",
    "ConditionalStyleAddSuccess": "Conditional style condition added.",
    "ConditionalStyleNewSuccess": "Ready to create a new conditional style.",
    "ConditionalStyleLoadSuccess": "Conditional style condition loaded.",
    "ConditionalStyleUpdateSuccess": "Conditional style condition updated.",
    "ConditionalStyleRemoveSuccess": "Conditional style condition removed.",
    "ConditionalStyleMoveUpSuccess": "Conditional style condition moved up.",
    "ConditionalStyleMoveDownSuccess": "Conditional style condition moved down.",
    "ConditionalStyleMoveBoundary": "Cannot move the selected condition further.",
    "ConditionalStyleResetSuccess": "Conditional style JSON cleared.",
    "ConditionalStyleActionFailed": "Failed to process the conditional style action.",
    "OperatorEquals": "Equals",
    "OperatorNotEquals": "Does not equal",
    "OperatorContains": "Contains",
    "OperatorNotContains": "Does not contain",
    "OperatorStartsWith": "Starts with",
    "OperatorEndsWith": "Ends with",
    "OperatorGreaterThan": "Greater than",
    "OperatorGreaterThanOrEqual": "Greater than or equal",
    "OperatorLessThan": "Less than",
    "OperatorLessThanOrEqual": "Less than or equal",
    "LogicalAnd": "AND",
    "LogicalOr": "OR",
    "FontStyleNormal": "Normal",
    "FontStyleItalic": "Italic",
    "FontStyleOblique": "Oblique",
    "FontStyleInitial": "Initial",
    "FontStyleInherit": "Inherit",
    "FontStyleUnset": "Unset",
    "FontWeightNormal": "Normal",
    "FontWeightBold": "Bold",

    "DiagnosticsGroupName": "Diagnostics",
    "PropEnableDiagnosticsLabel": "Enable diagnostic console logging",

    "NoListIconText": "Configure your calendar",
    "NoListConfigured": "Please choose an Events list in the web part properties in order to show a calendar",
    "NoListBtn": "Configure",
    "LoadingMessage": "Loading events\u2026",
    "LoadErrorMessage": "Unable to load events."
  }
});
