define([], function() {
  return {
    "PropertyPaneDescription": "动态表单配置",
    "BasicGroupName": "基本设置",
    "DescriptionFieldLabel": "描述",
    "PropertyGroupBasic": "基本设置",
    "PropertyGroupDefaults": "默认值",
    "PropertyGroupButtons": "按钮配置",
    "PropertyGroupConfigIO": "配置导入/导出",
    "PropListLabel": "SharePoint 列表",
    "PropModeLabel": "表单模式",
    "PropModeNew": "新建",
    "PropModeEdit": "编辑",
    "PropModeView": "查看",
    "PropItemIdQueryParamLabel": "ItemId 参数名",
    "PropDynamicItemIdLabel": "动态 Item ID（来自其他 WebPart）",
    "PropDynamicSourceNone": "没有可用的 ListControl 数据源",
    "PropUseDynamicItemAsItemIdLabel": "将动态 ID 作为表单项 ID",
    "PropUseDynamicItemAsItemIdHelp": "打开时：动态值（例如来自 ListControl 的 ID=1）直接用作在此表单列表中加载/编辑的记录 ID。关闭时：动态值仅用作字段值或筛选条件。",
    "PropDynamicItemTargetFieldLabel": "动态 ID 目标字段（id/内部名）",
    "PropDynamicItemTargetFieldPlaceholder": "例如：ParentId 或 ParentLookup",
    "PropDynamicItemTargetFieldHelp": "字段名（或内部名），动态值应设置到该字段。此字段将自动填充动态值（例如，用 ListControl 的值填充 'Main' 查询字段）。与筛选切换开关独立工作。",
    "PropDynamicTargetFieldNone": "所选列表没有可用字段",
    "PropertyPanelChoiceDisplay": "选项显示方式",
    "PropertyPanelChoiceDisplayDropdown": "下拉框",
    "PropertyPanelChoiceDisplayRadio": "单选按钮",
    "PropertyPanelChoiceDisplayMultiHint": "多选字段会显示为复选框。下面选择一个值后，可将其设为独占并清除其他选择。",
    "PropertyPanelExclusiveChoiceValue": "独占选项值",
    "PropertyPanelExclusiveChoiceValuePlaceholder": "例如：无",
    "PropertyPanelExclusiveChoiceValueHint": "当选择此值时，其他选项会被清除并禁用。",
    "PropPermissionBaseLookupFieldLabel": "用于权限判断的列",
    "PropPermissionBaseLookupFieldClear": "无（使用表单列表权限）",
    "PropPermissionBaseLookupFieldNone": "所选列表没有可用的查找列",
    "PropPermissionScopeLabel": "权限范围",
    "PropPermissionScopeList": "列表",
    "PropPermissionScopeItem": "项目",
    "PropUseDynamicValueAsFilterLabel": "使用动态值查找记录（筛选模式）",
    "PropUseDynamicValueAsFilterHelp": "打开时：动态值用于搜索匹配记录，方法是查找特定列等于动态值的记录。目标列由\"动态 ID 目标字段\"设置或在\"记录筛选 JSON\"中定义。关闭时：动态值仅用作字段值（无筛选）。",
    "PropFilterJsonLabel": "记录筛选 JSON",
    "PropFilterJsonPlaceholder": "[{\"field\":\"Main\",\"type\":\"lookup\",\"value\":\"dynamic\"}]",
    "PropFilterJsonHelp": "JSON 数组，用于定义查找要编辑/查看的记录的筛选条件。使用 \"dynamic\" 作为值来引用动态数据源值。类型：lookup、choice、text、number、boolean。",
    "PropFilterDesignerTitle": "筛选 JSON 设计器",
    "PropFilterDesignerFieldLabel": "筛选字段",
    "PropFilterDesignerTypeLabel": "字段类型",
    "PropFilterDesignerValueSourceLabel": "值来源",
    "PropFilterDesignerValueSourceDynamic": "动态值",
    "PropFilterDesignerValueSourceStatic": "固定值",
    "PropExpressionValueType": "表达式",
    "PropExpressionLabel": "表达式",
    "PropExpressionPlaceholder": "例如：today、date(-3) 或 me.email",
    "PropExpressionHelp": "支持的表达式：today、now、date(n)、me、me.email、me.login 和 me.id。date(n) 表示从今天偏移 n 天，例如 date(-3) 或 date(7)。",
    "PropExpressionHelpShow": "显示支持的表达式",
    "PropExpressionHelpHide": "隐藏支持的表达式",
    "PropExpressionInvalid": "请输入支持的表达式：today、now、date(n)、me、me.email、me.login 或 me.id。",
    "PropFilterDesignerValueLabel": "固定值",
    "PropFilterDesignerAddButtonLabel": "将条件添加到 JSON",
    "PropFilterDesignerExistingLabel": "现有条件",
    "PropFilterDesignerExistingNone": "JSON 中暂无条件",
    "PropFilterDesignerLoadButtonLabel": "加载所选条件",
    "PropFilterDesignerUpdateButtonLabel": "更新所选条件",
    "PropFilterDesignerRemoveButtonLabel": "删除所选条件",
    "PropFilterDesignerResetButtonLabel": "清空筛选 JSON",
    "PropFilterDesignerStatusPlaceholder": "筛选设计器结果显示在这里。",
    "PropValidateFilterJsonButtonLabel": "验证记录筛选 JSON",
    "PropDynamicModeLabel": "动态模式（new/edit/view）",
    "PropItemIdLabel": "Item ID",
    "PropItemIdPlaceholder": "可选：输入固定的 Item ID（用于编辑/查看）",
    "PropItemIdHelp": "可选固定记录 ID，用于直接打开。",
    "PropLabelPositionLabel": "标签位置",
    "PropLabelTop": "上方",
    "PropLabelLeft": "左侧",
    "PropShowFieldDescriptionLabel": "显示字段描述",
    "PropEnableDynamicDiagnosticsLabel": "启用动态诊断",
    "PropToggleOn": "显示",
    "PropToggleOff": "隐藏",
    "PropAddSubmitButtonLabel": "新增按钮文字",
    "PropAddSubmitButtonPlaceholder": "新增（默认）",
    "PropEditSubmitButtonLabel": "编辑按钮文字",
    "PropEditSubmitButtonPlaceholder": "保存（默认）",
    "PropSubmitButtonLabel": "提交按钮文字",
    "PropSubmitButtonPlaceholder": "提交（默认）",
    "PropShowCancelButtonLabel": "显示取消按钮",
    "PropCancelButtonLabel": "取消按钮文字",
    "PropCancelButtonPlaceholder": "取消（默认）",
    "PropCancelRedirectUrlLabel": "取消后跳转URL",
    "PropCancelRedirectUrlPlaceholder": "留空则重置表单",
    "PropSubmitRedirectUrlLabel": "提交后跳转URL",
    "PropSubmitRedirectUrlPlaceholder": "留空则显示成功消息",
    "PropSubmitSuccessMessageLabel": "提交成功消息",
    "PropSubmitSuccessMessagePlaceholder": "表单提交成功！（默认）",
    "PropButtonTextColorLabel": "按钮文字颜色",
    "PropButtonBackgroundColorLabel": "按钮背景颜色",
    "PropButtonBorderColorLabel": "按钮边框颜色",
    "PropButtonBorderWidthLabel": "按钮边框宽度",
    "PropButtonFontFamilyLabel": "按钮字体",
    "PropButtonFontSizeLabel": "按钮字体大小",
    "PropButtonFontStyleLabel": "按钮字体样式",
    "PropButtonFontBoldLabel": "按钮字体加粗",
    "PropButtonCornerStyleLabel": "按钮圆角样式",
    "PropButtonCornerRadiusLabel": "按钮圆角半径（px）",
    "PropCornerStyleSquare": "直角",
    "PropCornerStyleRounded": "圆角",
    "PropFontStyleNormal": "常规",
    "PropFontStyleItalic": "斜体",
    "PropDefaultValuesJsonLabel": "默认值 JSON（新增模式）",
    "PropDefaultValuesJsonPlaceholder": "{\n  \"Category\": \"IT\",\n  \"RequestType\": \"New\",\n  \"DepartmentLookup\": 1,\n  \"IsActive\": true\n}",
    "PropDefaultValuesJsonHelp": "可按字段内部名称或字段 id 设置默认值。在新建记录时生效（也包括编辑/查看但未解析到 item ID 的情况）。",
    "PropDefaultDesignerTitle": "默认值 JSON 设计器",
    "PropDefaultDesignerFieldLabel": "默认值字段",
    "PropDefaultDesignerValueTypeLabel": "默认值类型",
    "PropDefaultDesignerValueTypeString": "字符串",
    "PropDefaultDesignerValueTypeNumber": "数字",
    "PropDefaultDesignerValueTypeBoolean": "布尔",
    "PropDefaultDesignerValueTypeJson": "JSON",
    "PropDefaultDesignerValueLabel": "默认值",
    "PropDefaultDesignerAddButtonLabel": "添加/更新默认值到 JSON",
    "PropDefaultDesignerExistingLabel": "现有默认值",
    "PropDefaultDesignerExistingNone": "JSON 中暂无默认值",
    "PropDefaultDesignerLoadButtonLabel": "加载所选默认值",
    "PropDefaultDesignerRemoveButtonLabel": "删除所选默认值",
    "PropDefaultDesignerResetButtonLabel": "清空默认值 JSON",
    "PropDefaultDesignerStatusPlaceholder": "默认值设计器结果显示在这里。",
    "PropValidateDefaultValuesJsonButtonLabel": "验证默认值 JSON",
    "JsonValidationResultPlaceholder": "验证结果会显示在这里。",
    "JsonValidationSuccess": "JSON 格式有效。",
    "JsonValidationEmpty": "允许为空值。",
    "JsonValidationExpectedArray": "JSON 必须是数组。",
    "JsonValidationExpectedObject": "JSON 必须是对象。",
    "JsonValidationFailedPrefix": "JSON 无效",
    "ConfigExportButton": "导出配置",
    "ConfigImportButton": "导入配置",
    "ConfigImportSuccess": "配置已导入。",
    "ConfigImportInvalid": "配置文件无效。",
    "ConfigImportReadError": "读取配置文件失败。",
    "ConfigImportWarningList": "未找到列表，请在设置中重新选择列表。",
    "DesignerTitle": "表单设计器",
    "DesignerButton": "设计表单",
    "DesignerBackButton": "返回",
    "CommonSave": "保存",
    "CommonSaving": "保存中...",
    "CommonLoading": "加载中...",
    "CommonRetry": "重试",
    "CommonContinueEditing": "继续编辑",
    "CommonReadOnly": "只读",
    "CommonCancel": "取消",
    "CommonSubmit": "提交",
    "CommonSubmitting": "提交中...",
    "CommonContinueCreate": "继续新增",
    "CommonUnknownError": "未知错误",
    "RuntimeNoSchemaWarning": "请在 Web Part 属性中配置表单",
    "LoadErrorNoItemIdFromUrl": "无法从 URL、页面上下文或 WebPart 配置中解析 Item ID，无法加载表单数据。",
    "LoadConfigFailed": "加载表单配置失败",
    "SaveFailedDefault": "保存失败，请重试",
    "UploadAttachmentFailedTemplate": "上传附件 \"{0}\" 失败: {1}",
    "FormInvalidMessageDefault": "格式不正确",
    "FormStepValidationError": "请完成所有必填项后再继续",
    "FormSubmitFailedDefault": "提交失败，请重试",
    "FormRedirectFailed": "跳转失败：目标地址不在允许范围内。",
    "FormSubmitLabelEdit": "保存",
    "FormSubmitLabelAdd": "新增",
    "FormSwitchToEditLabel": "编辑",
    "FormSubmitSuccessEdit": "更新成功！",
    "FormSubmitSuccessNew": "提交成功！",
    "FormStepHiddenTitle": "当前容器不可见",
    "FormStepHiddenDescription": "请通过其他字段的配置来控制此容器的显示",
    "FormUploadingAttachments": "正在上传附件",
    "FormErrorSummaryTitle": "表单还有 {0} 处错误：",
    "DialogCancelTitle": "确认取消",
    "DialogCancelSubText": "当前有未保存的修改，确定要放弃这些更改吗？",
    "DialogDiscardChanges": "放弃修改",
    "StepPrev": "上一步",
    "StepNext": "下一步",
    "StepEmptyNoVisibleFields": "此容器没有可显示的字段",
    "FieldPlaceholderSelect": "请选择",
    "FieldUrlDescriptionLabel": "描述（可选）",
    "FieldUrlDescriptionPlaceholder": "链接显示的文本",
    "FieldUrlInvalidFormat": "URL 必须以 http:// 或 https:// 开头",
    "FieldErrorBoundaryMessage": "字段\"{0}\"渲染失败，请检查字段配置。",
    "FieldRichTextEmpty": "暂无内容",
    "FieldImageReadFileFailed": "无法读取文件内容",
    "FieldImageUploadFailed": "上传图片失败",
    "FieldImageInvalidFileType": "不支持的文件类型，仅允许 JPG、PNG、GIF、BMP 和 WebP 格式的图片。",
    "FieldImageNoImage": "无图片",
    "FieldImageRuntimeOnly": "图片选择器在运行模式下可用",
    "FieldPersonMissingContext": "缺少 SharePoint Context",
    "FieldPersonPlaceholder": "输入姓名或邮箱搜索（至少3个字符）...",
    "FieldAttachmentMissingContext": "缺少 SharePoint Context",
    "FieldAttachmentNeedListName": "请在表单配置中指定列表名称",
    "FieldAttachmentLoadListFailed": "无法获取列表 \"{0}\" 的 ID",
    "FieldAttachmentLoadingList": "正在加载列表信息...",
    "FieldAttachmentNeedListInfo": "请在表单配置中指定列表名称或列表 ID（GUID）以启用附件功能。",
    "FieldAttachmentUploadOnSubmit": "附件将在提交时统一上传。",
    "FieldAttachmentAddButton": "添加附件",
    "FieldAttachmentClear": "清空",
    "FieldAttachmentDelete": "删除",
    "FieldAttachmentUndoDelete": "撤销",
    "FieldAttachmentWillDelete": "将在提交时删除",
    "FieldAttachmentRemoveAria": "移除附件",
    "FieldAttachmentEmpty": "尚未选择附件",
    "FieldTaxonomyMissingContext": "缺少 SharePoint Context",
    "FieldTaxonomyMissingTermSetId": "缺少术语集 ID (TermSetId)",
    "FieldTaxonomyWorkbenchTitle": "Workbench 环境限制",
    "FieldTaxonomyWorkbenchDesc": "Taxonomy 字段在本地 Workbench 中不可用，需要部署到 SharePoint 才能测试。",
    "FieldTaxonomyDeployLink": "部署到 SharePoint",
    "FieldTaxonomyWorkbenchPlaceholder": "（仅在真实 SharePoint 环境中可用）",
    "FieldTaxonomyWorkbenchDescription": "此为占位符，请部署到 SharePoint 后测试完整功能",
    "FieldTaxonomyInvalidTermSetId": "无效的术语集 ID 格式: {0}",
    "FieldTaxonomyPanelTitle": "选择{0}",
    "FieldTaxonomyPlaceholder": "选择术语...",
    "FieldBooleanYes": "是",
    "FieldBooleanNo": "否",
    "ValidationRequired": "{0}为必填项",
    "ValidationMinLength": "最小长度为 {0}",
    "ValidationMaxLength": "最大长度为 {0}",
    "ValidationMinValue": "最小值为 {0}",
    "ValidationMaxValue": "最大值为 {0}",
    "ValidationPattern": "格式不正确",
    "DesignerLoadFieldsFailed": "加载字段失败",
    "DesignerNoListSelected": "未选择列表",
    "DesignerStepNotFound": "未找到容器",
    "DesignerAttachmentAlreadyExists": "附件字段已存在",
    "DesignerStepDefaultTitle": "容器 {0}",
    "DesignerAddStep": "+ 添加容器",
    "DesignerDeleteStep": "删除容器",
    "DesignerStepTitlePlaceholder": "容器标题",
    "DesignerStepDescriptionPlaceholder": "容器描述",
    "DesignerShowStep": "显示此容器",
    "DesignerShowStepHelp": "取消勾选后，此容器将默认隐藏，可通过其他字段的配置来控制显示（例如：点击按钮后显示）",
    "DesignerStepLayout": "容器布局",
    "DesignerLayoutStack": "垂直堆叠",
    "DesignerLayoutGrid": "网格布局",
    "DesignerColumns": "列数",
    "DesignerColumnOption": "{0}列",
    "DesignerRichTextChip": "富文本",
    "DesignerColumnBadge": "{0}列",
    "DesignerDelete": "删除",
    "DesignerEdit": "编辑",
    "DesignerMoveUp": "上移",
    "DesignerMoveDown": "下移",
    "DesignerStartNewRow": "从新行开始",
    "DesignerFormName": "表单名称",
    "DesignerFieldPickerTitle": "选择要添加的字段",
    "DesignerFieldTypeAndInternal": "类型: {0} | 内部名称: {1}",
    "DesignerAddFieldTooltip": "点击添加字段",
    "DesignerAddFieldHere": "+ 在此处添加字段",
    "DesignerClickAddField": "点击下方按钮添加字段",
    "DesignerAddFirstField": "+ 添加第一个字段",
    "DesignerRequiredFieldTitle": "必填",
    "DesignerPaletteListFields": "列表字段",
    "DesignerCustomFields": "自定义字段",
    "DesignerCustomFieldsDesc": "通过右侧按钮添加字段（不保存到 SharePoint）",
    "DesignerSPFields": "SharePoint 字段",
    "DesignerAddableFieldsCount": "可添加字段（{0}）",
    "DesignerNoAddableFields": "已没有可添加的字段",
    "DesignerCustomRichTextTitle": "富文本编辑器",
    "DesignerCustomRichTextDesc": "用于输入说明文字、提示信息等",
    "DesignerRichTextPlaceholder": "在此输入富文本内容...",
    "DesignerFieldTypeLabel": "{0} 字段",
    "PropertyPanelTitle": "字段属性",
    "PropertyPanelFieldInfo": "字段信息",
    "PropertyPanelFieldName": "字段名：",
    "PropertyPanelFieldType": "字段类型：",
    "PropertyPanelFieldInternalName": "内部名称：",
    "PropertyPanelFieldRequired": "必填：",
    "PropertyPanelFieldMaxLength": "最大长度：",
    "PropertyPanelFieldChoices": "选项：",
    "PropertyPanelFieldLookupList": "查找列表：",
    "PropertyPanelColumnSpan": "列跨度",
    "PropertyPanelColumnSpanDesc": "设置字段占据的列数。仅在网格布局下生效。",
    "PropertyPanelColumnSpanHint": "例如：在3列布局中，设置为2则该字段占据2列宽度",
    "PropertyPanelHelpText": "字段提示",
    "PropertyPanelHelpTextDesc": "显示在字段下方的说明文字，可用于示例或填写提示。",
    "PropertyPanelHelpTextPlaceholder": "例如：请输入完整部门名称",
    "PropertyPanelDefaultsGroup": "默认值",
    "PropertyPanelDefaultsGroupDesc": "在新建记录（新增模式）时生效。",
    "PropertyPanelDefaultText": "默认文本",
    "PropertyPanelDefaultTextPlaceholder": "输入默认文本",
    "PropertyPanelDefaultNumber": "默认数字",
    "PropertyPanelDefaultNumberPlaceholder": "输入默认数字",
    "PropertyPanelDefaultDateTime": "默认日期时间",
    "PropertyPanelDateFormat": "日期字段格式",
    "PropertyPanelDateFormatDateOnly": "仅日期",
    "PropertyPanelDateFormatDateTime": "日期和时间",
    "PropertyPanelDefaultBoolean": "默认选中",
    "PropertyPanelDefaultChoice": "默认选项（新增模式）",
    "PropertyPanelDefaultChoiceEmpty": "该字段没有可用选项。",
    "PropertyPanelDefaultMultiSelect": "默认多选值（新增模式）",
    "PropertyPanelDefaultMultiSelectPlaceholder": "值A; 值B",
    "PropertyPanelDefaultMultiSelectHint": "使用分号分隔多个默认值。",
    "PropertyPanelDefaultLookupId": "默认查找项 ID（新增模式）",
    "PropertyPanelDefaultLookupIdPlaceholder": "输入查找项 ID，例如 1",
    "PropertyPanelDefaultLookupIdHint": "在新建记录时，使用目标列表项 ID 预选查找值。",
    "PropertyPanelAttachmentAllowDelete": "允许删除现有附件",
    "PropertyPanelAttachmentAllowDeleteHint": "禁用后，现有附件将以只读方式显示，用户无法将其标记为删除。",
    "PropertyPanelDefaultUnsupportedHint": "该字段类型暂不支持默认值。",
    "PropertyPanelDefaultNone": "无",
    "PropertyPanelRichTextContent": "富文本内容",
    "PropertyPanelRichTextDesc": "编辑富文本字段的内容，这些内容将在表单中显示。",
    "PropertyPanelMissingSPField": "未找到对应的 SharePoint 字段信息，部分配置可能无法正确显示。",
    "PropertyFieldTypeText": "单行文本",
    "PropertyFieldTypeMultiline": "多行文本",
    "PropertyFieldTypeNumber": "数字",
    "PropertyFieldTypeDatetime": "日期时间",
    "PropertyFieldTypeDropdown": "下拉选择",
    "PropertyFieldTypeMultiselect": "多选",
    "PropertyFieldTypeLookup": "查找",
    "PropertyFieldTypePerson": "人员",
    "PropertyFieldTypeBoolean": "是/否",
    "PropertyFieldTypeImage": "图片",
    "PropertyFieldTypeUrl": "超链接",
    "PropertyFieldTypeTaxonomy": "托管元数据",
    "PropertyFieldTypeAttachment": "附件",
    "PropertyFieldTypeRichtext": "富文本",
    "ConditionOpEq": "等于",
    "ConditionOpNe": "不等于",
    "ConditionOpGt": "大于",
    "ConditionOpGe": "大于或等于",
    "ConditionOpLt": "小于",
    "ConditionOpLe": "小于或等于",
    "ConditionOpContains": "包含",
    "ConditionOpStartsWith": "开始于",
    "ConditionVisibilityLabel": "可见性条件",
    "ConditionVisibilityDesc": "设置字段何时显示。留空则始终显示。",
    "ConditionNoRules": "暂无条件设置，字段将始终显示",
    "ConditionRuleLabel": "条件 {0}",
    "ConditionFieldLabel": "字段",
    "ConditionFieldPlaceholder": "选择字段",
    "ConditionOperatorLabel": "操作符",
    "ConditionValueLabel": "值",
    "ConditionValuePlaceholder": "输入比较的值",
    "ConditionAnd": "且",
    "ConditionAdd": "+ 添加条件",
    "ConditionHint": "提示：所有条件之间是“与”的关系（必须同时满足）。例如：部门等于“IT” 且状态不等于“已关闭”。",
    "AppLocalEnvironmentSharePoint": "应用正在本地环境作为 SharePoint Web Part 运行",
    "AppLocalEnvironmentTeams": "应用正在本地环境作为 Microsoft Teams 应用运行",
    "AppLocalEnvironmentOffice": "应用正在本地环境在 office.com 运行",
    "AppLocalEnvironmentOutlook": "应用正在本地环境在 Outlook 运行",
    "AppSharePointEnvironment": "应用正在 SharePoint 页面运行",
    "AppTeamsTabEnvironment": "应用正在 Microsoft Teams 运行",
    "AppOfficeEnvironment": "应用正在 office.com 运行",
    "AppOutlookEnvironment": "应用正在 Outlook 运行",
    "UnknownEnvironment": "应用正在未知环境运行"
  }
});
