import { DisplayMode } from '@microsoft/sp-core-library';
import { WebPartContext } from '@microsoft/sp-webpart-base';

export interface ICalendarDataSource {
  listName: string;
  targetPageUrl?: string;
  startFieldName?: string;
  endFieldName?: string;
  backgroundColor?: string;
  baseTemplate?: number;
}

export interface ICalendarProps {
  title: string;
  description: string;
  displayMode: DisplayMode;
  spfxContext: WebPartContext;
  listName: string;
  dataSources: ICalendarDataSource[];
  defaultView: string;
  showWeekends: boolean;
  showMonthEventStartTime: boolean;
  showMonthEventDuration: boolean;
  calendarHeight: number;
  enableSwimlanes: boolean;
  swimlaneFieldName: string;
  swimlaneDays: number;
  swimlaneUnassignedLabel: string;
  filterJson: string;
  conditionalStyleJson: string;
  showLinkToItem: boolean;
  enableEventDetails: boolean;
  eventDetailsFields: any[];
  eventDetailsFieldsJson: string;
  fieldMetadata: { [internalName: string]: { type: string; richText: boolean } };
  detailsLinkPresentation: string;
  linkTargetPageUrl: string;
  linkTargetIdParam: string;
  includeReturnUrlParam: boolean;
  calendarBackgroundColor: string;
  webPartBorderColor: string;
  webPartBorderWidth: number;
  webPartCornerRadius: number;
  webPartTitleTextColor: string;
  webPartTitleFontFamily: string;
  webPartTitleFontSize: string;
  webPartTitleFontStyle: string;
  webPartTitleFontBold: boolean;
  webPartTitleAlignment: string;
  webPartTitleBackgroundColor: string;
  webPartTitleMinHeight: number;
  webPartDescriptionTextColor: string;
  webPartDescriptionFontFamily: string;
  webPartDescriptionFontSize: string;
  webPartDescriptionFontStyle: string;
  webPartDescriptionFontBold: boolean;
  calendarTitleTextColor: string;
  calendarTitleFontFamily: string;
  calendarTitleFontSize: string;
  calendarTitleFontStyle: string;
  calendarTitleFontBold: boolean;
  toolbarButtonBackgroundColor: string;
  toolbarButtonTextColor: string;
  toolbarButtonBorderColor: string;
  toolbarButtonActiveBackgroundColor: string;
  toolbarButtonActiveTextColor: string;
  toolbarButtonFontFamily: string;
  toolbarButtonFontSize: string;
  toolbarButtonFontStyle: string;
  toolbarButtonFontBold: boolean;
  toolbarButtonBorderWidth: number;
  toolbarButtonCornerRadius: number;
  eventBackgroundColor: string;
  eventTextColor: string;
  eventBorderColor: string;
  eventFontFamily: string;
  eventFontSize: string;
  eventFontStyle: string;
  eventFontBold: boolean;
  eventBorderWidth: number;
  eventCornerRadius: number;
  selectedEventBackgroundColor: string;
  selectedEventTextColor: string;
  selectedEventBorderColor: string;
  selectedEventFontFamily: string;
  selectedEventFontSize: string;
  selectedEventFontStyle: string;
  selectedEventFontBold: boolean;
  selectedEventBorderWidth: number;
  selectedEventCornerRadius: number;
  detailsPanelBackgroundColor: string;
  detailsPanelBorderColor: string;
  detailsPanelBorderWidth: number;
  detailsPanelCornerRadius: number;
  detailsPanelMaxWidth: number;
  detailsPanelPadding: number;
  detailsPanelShadow: boolean;
  detailsOverlayColor: string;
  detailsOverlayOpacity: number;
  detailsTitleTextColor: string;
  detailsTitleFontFamily: string;
  detailsTitleFontSize: string;
  detailsTitleFontStyle: string;
  detailsTitleFontBold: boolean;
  detailsLabelTextColor: string;
  detailsLabelFontFamily: string;
  detailsLabelFontSize: string;
  detailsLabelFontStyle: string;
  detailsLabelFontBold: boolean;
  detailsValueTextColor: string;
  detailsValueFontFamily: string;
  detailsValueFontSize: string;
  detailsValueFontStyle: string;
  detailsValueFontBold: boolean;
  detailsDividerColor: string;
  detailsDividerWidth: number;
  detailsCloseButtonColor: string;
  detailsCloseButtonBackgroundColor: string;
  detailsCloseButtonHoverBackgroundColor: string;
  detailsCloseButtonCornerRadius: number;
  enableDiagnostics: boolean;
  onEventSelectionChange: (itemId: number, mode: string) => void;
  fUpdateProperty: (value: string) => void;
  fPropertyPaneOpen: () => void;
}
