define([], function() {
  return {
    "PropertyPaneDescription": "Contacts Web Part",
    "BasicGroupName": "Data Source",
    "ListConfigGroupName": "Columns to Use",
    "ListChoicesGroupName": "List Items",
    "overRideCSS": "Override CSS URL",
    "CommonGroupName": "Common Properties",
    "HeaderStyleGroupName": "Header Properties",
    "TitleStyleGroupName": "Title Properties",
    "PropEnableDiagnosticsLabel": "Enable diagnostics logging",
    "DirectorateFieldLabel": "Directorate",
    "DivisionFieldLabel": 'Division',
    "EucomListUrl": "/Lists/ISKMSP2019PersonnelWidget",
    "PersonnelImgWidth": "Image Width",
    "CustomListAddItem": "Add item",
    "CustomListBack": "Back",
    "CustomListTrue": "True",
    "CustomListFalse": "False",
    "CustomListOK": "OK",
    "CustomListCancel": "Cancel",
    "CustomListEdit": "Edit",
    "CustomListDel": "Del",
    "CustomListYes": "Yes",
    "CustomListNo": "No",
    "CustomListConfirmDel": "Confirm Delete",
    "CustomListConformDelMssg": "Are you sure that you want to delete this item ?",
    "CustomListFieldMissing": "Error the field '{0}' is mandatory",
     //PicturePicker labels
     "PicturePickerTitle": "Select a picture",
     "PicturePickerRecent": "Recent",
     "PicturePickerSite": "Site",
     "PicturePickerButtonSelect": "Select a picture",
     "PicturePickerButtonReset": "Reset",
      //DocumentPicker labels
    "DocumentPickerTitle": "Select a document",
    "DocumentPickerRecent": "Recent",
    "DocumentPickerSite": "Site",
    "DocumentPickerButtonSelect": "Select a document",
    "DocumentPickerButtonReset": "Reset"
  }
});