define([], function() {
  return {
    "PropertyPaneDescription": "List control settings",
    "PropertyPanePageGuideTitle": "Page Guide",
    "PropertyPanePageGuideFilters": "Page 2: Build preset filters.",
    "PropertyPanePageGuideStyles": "Page 3: Configure conditional styles.",
    "PropertyGroupData": "Data",
    "PropertyGroupButtons": "Buttons",
    "PropertyGroupBodyStyle": "Body text style",
    "PropertyGroupDateDisplay": "Date display",
    "PropertyGroupSelectedStyle": "Selected row style",
    "PropertyGroupHeaderStyle": "Header style",
    "PropInstanceNameLabel": "Web part name",
    "PropInstanceNameDescription": "Used to identify this List Control in Dynamic Form web part connections. Leave blank to use the default name.",
    "PropListLabel": "SharePoint list",
    "PropViewLabel": "Default view",
    "PropViewPlaceholder": "Select a view",
    "PropNoViews": "No views available",
    "PropViewColumnsLabel": "View columns",
    "PropViewColumnsHeader": "Displayed columns (use Move up/Move down to change order)",
    "PropViewColumnField": "Column",
    "PropViewColumnDisplayName": "Display name",
    "PropViewColumnWidth": "Width (px; blank = auto)",
    "PropListDesignerButton": "Open List Designer",
    "PropListDesignerConfigured": "{0} columns configured.",
    "PropListDesignerGrouped": "Grouping enabled.",
    "PropPageSizeLabel": "Items per page",
    "PropPageSizeDescription": "Leave blank or enter 0 for Automatic (50). Maximum 100.",
    "PropFetchBatchSizeLabel": "Fetch batch size",
    "PropFetchBatchSizeDescription": "Items requested from SharePoint at a time. Default 500; minimum 100; maximum 2000.",
    "PropShowViewSelectorLabel": "Show view label and dropdown",
    "PropShowViewAsDropdownLabel": "Show view as dropdown (uncheck to show view name only, read-only)",
    "PropShowLinkToItemLabel": "Show Link to Item",
    "PropLinkTargetPageUrlLabel": "Link target page",
    "PropLinkTargetPageUrlPlaceholder": "/SitePages/DynamicForm.aspx",
    "PropLinkTargetDefaultFormOption": "Display List Default Form",
    "PropLinkTargetSavedUrlLabel": "saved URL",
    "PropLinkTargetIdParamLabel": "Link target ID parameter",
    "PropLinkTargetIdParamPlaceholder": "itemid",
    "PropIncludeReturnUrlParamLabel": "Include return URL parameter (return)",
    "PropEnableDiagnosticsLabel": "Enable diagnostics logging",
    "PresetFilterPageTitle": "Preset filters",
    "PresetFilterDesignerGroupName": "Preset filter designer",
    "PresetFilterJsonGroupName": "Preset filter JSON",
    "PropFilterJsonLabel": "Preset filter JSON",
    "PropFilterJsonPlaceholder": "[{\"field\":\"Title\",\"operator\":\"contains\",\"logical\":\"and\",\"value\":\"abc\"}]",
    "PropFilterJsonHelp": "JSON array of preset filter conditions applied to list rows before user filters.",
    "PropFilterDesignerFieldLabel": "Filter field",
    "PropFilterDesignerFieldNone": "No fields available for filter designer",
    "PropFilterDesignerOperatorLabel": "Operator",
    "PropFilterDesignerLogicalLabel": "Logical",
    "PropFilterDesignerLogicalAnd": "AND",
    "PropFilterDesignerLogicalOr": "OR",
    "PropFilterDesignerValueTypeLabel": "Value type",
    "PropFilterDesignerValueTypeStatic": "Static value",
    "PropFilterDesignerValueTypeExpression": "Expression",
    "PropFilterDesignerValueLabel": "Value",
    "PropFilterDesignerValuePlaceholder": "Enter value",
    "PropFilterDesignerExpressionLabel": "Expression",
    "PropFilterDesignerExpressionPlaceholder": "today, date(-3), or me",
    "PropFilterDesignerExpressionHelp": "Supported: today, now, date(n), me, me.email, me.login, and me.id. date(n) offsets today by n days.",
    "PropFilterDesignerExpressionHelpShow": "Show supported expressions",
    "PropFilterDesignerExpressionHelpHide": "Hide supported expressions",
    "PropFilterDesignerExpressionInvalid": "Enter a supported expression: today, now, date(n), me, me.email, me.login, or me.id.",
    "PropFilterDesignerAddButtonLabel": "Add condition to JSON",
    "PropFilterDesignerExistingLabel": "Existing conditions",
    "PropFilterDesignerExistingNone": "No conditions in JSON",
    "PropFilterDesignerLoadButtonLabel": "Load selected condition",
    "PropFilterDesignerUpdateButtonLabel": "Update selected condition",
    "PropFilterDesignerRemoveButtonLabel": "Remove selected condition",
    "PropFilterDesignerResetButtonLabel": "Clear filter JSON",
    "PropFilterDesignerStatusPlaceholder": "Filter designer result appears here.",
    "PropFilterDesignerFieldRequired": "Select a field before adding or updating a condition.",
    "PropFilterDesignerValueRequired": "Enter a value before adding or updating a condition.",
    "PropFilterDesignerSelectValid": "Select a valid condition first.",
    "PropFilterDesignerAddSuccess": "Condition added to preset filter JSON.",
    "PropFilterDesignerLoadSuccess": "Condition loaded into designer fields.",
    "PropFilterDesignerUpdateSuccess": "Selected condition updated.",
    "PropFilterDesignerRemoveSuccess": "Selected condition removed.",
    "PropFilterDesignerResetSuccess": "Preset filter JSON cleared.",
    "PropFilterDesignerActionFailed": "Failed to process filter designer action.",
    "PropValidateFilterJsonButtonLabel": "Validate preset filter JSON",
    "JsonValidationResultPlaceholder": "Validation result appears here.",
    "JsonValidationSuccess": "JSON is valid.",
    "JsonValidationEmpty": "Empty value is allowed.",
    "JsonValidationExpectedArray": "JSON must be an array.",
    "JsonValidationExpectedObject": "JSON must be an object.",
    "JsonValidationFailedPrefix": "JSON is invalid",
    "ConditionalStylePageTitle": "Conditional styles",
    "ConditionalStyleSummaryGroupName": "Rule summary",
    "ConditionalStyleDesignerGroupName": "Conditional style designer",
    "ConditionalStyleJsonGroupName": "Conditional style JSON",
    "PropConditionalStyleFieldNone": "No fields available for conditional style designer",
    "PropConditionalStyleRuleNameLabel": "Rule name",
    "PropConditionalStyleRuleNamePlaceholder": "Example: CompleteRow",
    "PropConditionalStyleScopeLabel": "Apply style to",
    "PropConditionalStyleScopeRow": "Row",
    "PropConditionalStyleScopeColumn": "Column",
    "PropConditionalStyleApplyFieldLabel": "Target column (for column scope)",
    "PropConditionalStyleConditionFieldLabel": "Condition field",
    "PropConditionalStyleConditionOperatorLabel": "Condition operator",
    "PropConditionalStyleConditionLogicalLabel": "Condition logical",
    "PropConditionalStyleEnabledLabel": "Enable this rule",
    "PropConditionalStylePriorityLabel": "Priority",
    "PropConditionalStylePriorityPlaceholder": "100",
    "PropConditionalStyleConditionValueLabel": "Condition value",
    "PropConditionalStyleConditionValuePlaceholder": "Enter condition value",
    "PropConditionalStyleBackgroundColorLabel": "Background color override",
    "PropConditionalStyleForegroundColorLabel": "Foreground color override",
    "PropConditionalStyleBorderColorLabel": "Border color override",
    "PropConditionalStyleBorderStyleLabel": "Border type override",
    "PropConditionalStyleBorderWidthLabel": "Border thickness (px)",
    "PropConditionalStyleCornerStyleLabel": "Border corners",
    "PropConditionalStyleBorderRadiusLabel": "Border radius (px)",
    "PropConditionalStyleBorderDefault": "Default",
    "PropConditionalStyleBorderNone": "None",
    "PropConditionalStyleBorderSolid": "Solid",
    "PropConditionalStyleBorderDashed": "Dashed",
    "PropConditionalStyleBorderDotted": "Dotted",
    "PropConditionalStyleBorderDouble": "Double",
    "PropConditionalStyleCornerSquare": "Square",
    "PropConditionalStyleCornerRounded": "Rounded",
    "PropConditionalStyleFontFamilyLabel": "Font family override",
    "PropConditionalStyleFontSizeLabel": "Font size override",
    "PropConditionalStyleFontStyleLabel": "Font style override",
    "PropConditionalStyleFontWeightLabel": "Font weight override",
    "PropConditionalStyleTextAlignLabel": "Text align override",
    "PropConditionalStyleAddButtonLabel": "Add condition to JSON",
    "PropConditionalStyleNewButtonLabel": "New style",
    "PropConditionalStyleExistingLabel": "Existing conditional style conditions",
    "PropConditionalStyleExistingNone": "No conditional style conditions in JSON",
    "PropConditionalStyleLoadButtonLabel": "Load selected condition",
    "PropConditionalStyleUpdateButtonLabel": "Update selected condition",
    "PropConditionalStyleRemoveButtonLabel": "Remove selected condition",
    "PropConditionalStyleMoveUpButtonLabel": "Move selected condition up",
    "PropConditionalStyleMoveDownButtonLabel": "Move selected condition down",
    "PropConditionalStyleResetButtonLabel": "Clear conditional style JSON",
    "PropConditionalStyleStatusPlaceholder": "Conditional style designer result appears here.",
    "PropConditionalStyleJsonLabel": "Conditional style JSON",
    "PropConditionalStyleJsonPlaceholder": "[{\"rule\":\"CompleteRow\",\"scope\":\"row\",\"conditionField\":\"Status\",\"operator\":\"eq\",\"logical\":\"and\",\"value\":\"Complete\",\"style\":{\"backgroundColor\":\"#dff0d8\",\"color\":\"#2e6b2e\"}}]",
    "PropConditionalStyleJsonHelp": "JSON array of conditional style conditions. Use the same rule name across entries to create multi-condition rules.",
    "PropValidateConditionalStyleJsonButtonLabel": "Validate conditional style JSON",
    "ConditionalStyleJsonValidationResultPlaceholder": "Validation result appears here.",
    "PropConditionalStyleRuleNameRequired": "Enter a rule name before adding or updating a condition.",
    "PropConditionalStyleApplyFieldRequired": "Select the target column when scope is Column.",
    "PropConditionalStyleConditionFieldRequired": "Select a condition field before adding or updating.",
    "PropConditionalStyleConditionValueRequired": "Enter a condition value before adding or updating.",
    "PropConditionalStyleSelectValid": "Select a valid conditional style condition first.",
    "PropConditionalStyleAddSuccess": "Conditional style condition added.",
    "PropConditionalStyleNewSuccess": "Ready to create a new conditional style.",
    "PropConditionalStyleLoadSuccess": "Conditional style condition loaded.",
    "PropConditionalStyleUpdateSuccess": "Conditional style condition updated.",
    "PropConditionalStyleRemoveSuccess": "Conditional style condition removed.",
    "PropConditionalStyleMoveUpSuccess": "Conditional style condition moved up.",
    "PropConditionalStyleMoveDownSuccess": "Conditional style condition moved down.",
    "PropConditionalStyleMoveBoundary": "Cannot move the selected condition further.",
    "PropConditionalStyleResetSuccess": "Conditional style JSON cleared.",
    "PropConditionalStyleActionFailed": "Failed to process conditional style action.",
    "PropConditionalStyleSummaryNone": "No rules configured.",
    "PropConditionalStyleSummaryInvalid": "Unable to parse conditional style JSON.",
    "PropConditionalStyleSummaryEnabled": "enabled",
    "PropConditionalStyleSummaryDisabled": "disabled",
    "PropConditionalStyleSummaryPriorityPrefix": "P",
    "PropConditionalStyleSummaryScopeRow": "row",
    "PropConditionalStyleSummaryScopeColumn": "column:",
    "PropConditionalStyleSummaryConditionCountPrefix": "conditions:",
    "PropShowRefreshLabel": "Show Refresh button",
    "PropShowAddLabel": "Show Add button",
    "PropShowEditLabel": "Show Edit button",
    "PropShowViewLabel": "Show View button",
    "PropShowDeleteLabel": "Show Delete button",
    "PropButtonDisplayModeLabel": "Button display",
    "PropButtonDisplayModeText": "Text",
    "PropButtonDisplayModeIconText": "Icon and text",
    "PropButtonDisplayModeIcon": "Icon only",
    "PropBodyTextColorLabel": "Body text color (e.g. #222222)",
    "PropBodyFontFamilyLabel": "Body font family (e.g. Segoe UI)",
    "PropDateDisplayFormatLabel": "Date format",
    "PropDateDisplayFormatCustom": "Custom",
    "PropDateCustomFormatLabel": "Custom date format",
    "PropDateCustomFormatDescription": "Used for date-only fields. Tokens: YYYY, YY, MMMM, MMM, MM, M, DD, D, dddd, ddd. Example: MMM D, YYYY",
    "PropCustomFormatTextCaseLabel": "Text case",
    "PropCustomFormatTextCaseDefault": "Default",
    "PropCustomFormatTextCaseUpper": "UPPERCASE",
    "PropCustomFormatTextCaseLower": "lowercase",
    "PropTimeDisplayFormatLabel": "Time format",
    "PropTimeDisplayFormatCustom": "Custom",
    "PropTimeCustomFormatLabel": "Custom date/time format",
    "PropTimeCustomFormatDescription": "Fully replaces the output for date+time fields, so date and time tokens can be combined/reordered freely. Tokens: YYYY, YY, MMMM, MMM, MM, M, DD, D, dddd, ddd, HH, H (24-hour), hh, h (12-hour), mm, ss, tt (AM/PM). Example: dddd, MMMM D, YYYY hh:mm tt",
    "PropBodyFontSizeLabel": "Body font size",
    "PropBodyFontStyleLabel": "Body font style",
    "PropBodyTextAlignLabel": "Body text alignment",
    "PropBodyBoldLabel": "Body text bold",
    "PropSelectedTextColorLabel": "Selected row text color",
    "PropSelectedBackgroundColorLabel": "Selected row background color",
    "PropSelectedFontStyleLabel": "Selected row font style",
    "PropSelectedBoldLabel": "Selected row text bold",
    "PropHeaderTextColorLabel": "Header text color",
    "PropHeaderBackgroundColorLabel": "Header background color",
    "PropHeaderFontFamilyLabel": "Header font family",
    "PropHeaderFontSizeLabel": "Header font size",
    "PropHeaderFontStyleLabel": "Header font style",
    "PropHeaderTextAlignLabel": "Header text alignment",
    "PropHeaderBoldLabel": "Header text bold",
    "PropFontStyleNormal": "Normal",
    "PropFontStyleItalic": "Italic",
    "PropFontStyleOblique": "Oblique",
    "PropFontStyleInitial": "Initial",
    "PropFontStyleInherit": "Inherit",
    "PropFontStyleUnset": "Unset",
    "PropTextAlignLeft": "Left",
    "PropTextAlignCenter": "Center",
    "PropTextAlignRight": "Right",
    "RuntimeNoListSelected": "Configure a SharePoint list in the web part settings.",
    "RuntimeLoading": "Loading...",
    "RuntimeNoItems": "No items found for the selected view.",
    "RuntimeNoItemsAfterFilter": "No items match the active filters.",
    "RuntimeTotalItemsLabel": "Total items: {0}",
    "RuntimeLoadedItemsLabel": "Items loaded: {0}",
    "RuntimeBooleanYes": "Yes",
    "RuntimeBooleanNo": "No",
    "RuntimeGroupNoneValue": "(None)",
    "RuntimeGroupExpand": "Expand group",
    "RuntimeGroupCollapse": "Collapse group",
    "RuntimeGroupItemCount": "{0} items",
    "RuntimeSelectedItem": "Selected item ID: {0}",
    "RuntimeViewLabel": "View",
    "RuntimeRefresh": "Refresh",
    "RuntimeNew": "New",
    "RuntimeEdit": "Edit",
    "RuntimeView": "View",
    "RuntimeDelete": "Delete",
    "RuntimePreviousPage": "Previous",
    "RuntimeNextPage": "Next",
    "RuntimePageStatus": "Page {0} of {1} ({2} per page)",
    "RuntimePageStatusMore": "Page {0} of {1}+ ({2} per page)",
    "RuntimeLoadingMore": "Loading more items...",
    "RuntimeSortToggle": "Toggle sort direction",
    "RuntimeScrollLeft": "Scroll left",
    "RuntimeScrollRight": "Scroll right",
    "RuntimeFilterTitle": "Filter this column",
    "RuntimeFilterIcon": "Filter",
    "RuntimeFilterOperatorLabel": "Operator",
    "RuntimeFilterValueLabel": "Value",
    "RuntimeFilterValuePlaceholder": "Enter a value",
    "RuntimeFilterDateLabel": "Date",
    "RuntimeFilterEndDateLabel": "End date (optional)",
    "RuntimeFilterApply": "Apply",
    "RuntimeFilterClear": "Clear",
    "RuntimeFilterClose": "Close",
    "RuntimeFilterOperatorEquals": "Equals",
    "RuntimeFilterOperatorNotEquals": "Not equals",
    "RuntimeFilterOperatorContains": "Contains",
    "RuntimeFilterOperatorNotContains": "Does not contain",
    "RuntimeFilterOperatorStartsWith": "Starts with",
    "RuntimeFilterOperatorEndsWith": "Ends with",
    "RuntimeFilterOperatorGreaterThan": "Greater than",
    "RuntimeFilterOperatorGreaterThanOrEqual": "Greater than or equal",
    "RuntimeFilterOperatorLessThan": "Less than",
    "RuntimeFilterOperatorLessThanOrEqual": "Less than or equal",
    "RuntimeDeleteConfirm": "Delete the selected item?",
    "RuntimeDeleteSuccess": "Item deleted.",
    "RuntimeDeleteFailed": "Delete failed.",
    "RuntimeSelectRowPrompt": "Select a row to enable Edit, View, and Delete.",
    "RuntimeSelectedMode": "Selected mode: {0}",
    "RuntimeConditionalStyleMatches": "Matched style rules: {0}",
    "RuntimeConditionalStyleMatchesNone": "none",
    "DynamicSourceTitle": "List Control",
    "DynamicSourceDescription": "Publishes the selected SharePoint list item and desired form mode.",
    "DynamicPropertySelectedItemIdTitle": "Selected Item ID",
    "DynamicPropertySelectedItemIdDescription": "The ID of the currently selected row.",
    "DynamicPropertySelectedModeTitle": "Selected Mode",
    "DynamicPropertySelectedModeDescription": "The desired form mode: new, edit, or view.",
    "ColumnIdFallback": "ID",
    "PropertyGroupTableStyle": "Table style",
    "PropTableBackgroundColorLabel": "Table background color",
    "PropTableBorderColorLabel": "Table border color",
    "PropTableBorderWidthLabel": "Table border width",
    "PropTableRowLineWidthLabel": "Row line width",
    "PropTableCornerStyleLabel": "Table corner style",
    "PropTableCornerRadiusLabel": "Table corner radius (px)",
    "PropCornerStyleLabel": "Corner style",
    "PropCornerStyleSquare": "Square",
    "PropCornerStyleRounded": "Rounded",
    "PropCornerRadiusLabel": "Corner radius (px)",
    "PropAlternateRowShadingLabel": "Alternate row shading",
    "PropAlternateRowShadingColorLabel": "Alternate row shading color",
    "PropertyGroupButtonStyle": "Button style",
    "PropButtonTextColorLabel": "Button text color",
    "PropButtonBackgroundColorLabel": "Button background color",
    "PropButtonFontFamilyLabel": "Button font family",
    "PropButtonFontSizeLabel": "Button font size",
    "PropButtonFontStyleLabel": "Button font style",
    "PropButtonBoldLabel": "Button text bold",
    "PropButtonCornerStyleLabel": "Button corner style",
    "PropButtonCornerRadiusLabel": "Button corner radius (px)",
    "PropertyGroupWebpartStyle": "Webpart style",
    "PropWebpartBackgroundColorLabel": "Webpart background color",
    "PropWebpartBorderColorLabel": "Webpart border color",
    "PropWebpartBorderWidthLabel": "Webpart border width"
  };
});